-- Methods
INSERT INTO methods (name) VALUES ('Build') ON CONFLICT (name) DO NOTHING;
INSERT INTO methods (name) VALUES ('muddle and shake') ON CONFLICT (name) DO NOTHING;
INSERT INTO methods (name) VALUES ('Shake') ON CONFLICT (name) DO NOTHING;
INSERT INTO methods (name) VALUES ('shake and top') ON CONFLICT (name) DO NOTHING;
INSERT INTO methods (name) VALUES ('Stir') ON CONFLICT (name) DO NOTHING;
INSERT INTO methods (name) VALUES ('dry shake and shake') ON CONFLICT (name) DO NOTHING;

-- Glassware
INSERT INTO glassware (name) VALUES ('Coupette') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Custom') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Rocks') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Rocks & Crushed ice') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Small Rocks') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Spritz') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Flute') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Highball') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Fizz') ON CONFLICT (name) DO NOTHING;
INSERT INTO glassware (name) VALUES ('Ceramic') ON CONFLICT (name) DO NOTHING;

-- Families
INSERT INTO families (name) VALUES ('Tiki') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Sipper') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('champagne') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Punch') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Daiquiri') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Low ABV') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Aromatic') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Aperitif') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Spritz') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Highball') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Martini') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Manhatten') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Sour') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Fizz') ON CONFLICT (name) DO NOTHING;
INSERT INTO families (name) VALUES ('Negroni') ON CONFLICT (name) DO NOTHING;

-- Ingredients
INSERT INTO ingredients (name) VALUES ('Absinthe rinse glass') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('aged rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('x Flamed Orange Disc in Mixing Glass') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('port') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lemon juice') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('cointreu') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('apry') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Fresh Lemon Juice') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Michters rye') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('honey syrup 3:1') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('rye whiskey') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Scotch') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lime, 20ml ginger syrup, 50ml grey goose, top soda, candied ginger') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Fino') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('agricole') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Apricot Brandy') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dark rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('brown sugar cube') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Guinness') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('wonder foam') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Homey syrup') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('White Rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('orange bitters') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lime, 12.5ml ginger syrup, 12.5ml honey syrup, 40ml tequila, 7ml mezcal float') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Pisco') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Shake') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dry vermouth') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Egg shite') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Orange slice, 25ml lemon, 25ml sugar, 25ml cynar, 25ml gin') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Gin') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Honey 2:1') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Yellow Chartreuse') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Punt E Mes') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('sweet vermouth') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('float 10ml Cassis') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('10-15ml sugar') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('amaretto') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Bsp Marashino') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('fraise') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Bsp grenadine') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('gold rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Soda') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('House Vodka') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Lime juice') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Coganc') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('sugar') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('2-Dash Orange Bitters') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Campari') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Lillet') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('tequila') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('beefeater') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('amer picon') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Orange bitters') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dash Ango') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Fernet Brance') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Aperol, 15ml Campari, 45ml sweet vermouth, 2 dash absinthe, top soda') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('DOM Benedictine') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Bsp Absinthe') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Caretakers Gin') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dry Vermouth') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Rye') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('peychauds') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('house dry vermouth') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('bar spoon rasp jam') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('apricot') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Irish') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('fino style Sherry') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('cynar') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('angostura') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('islay float') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dolin') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Barbados rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Absinthe') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Cointreau') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('absinthe') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('cointreau') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lemon, 30ml ango, 30ml orgeat, 15ml rye') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Grey goose') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Cointreu') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dry red wine') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dash ango') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dash ango') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('calvados') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Apry') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('cassis') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('scotch') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('orange bitters, 30ml lime, 20ml grenadine, 50ml gin') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('1-Dash Orange Bitters') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Sweet Vermouth') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('gin') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('maraschino') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dry triple sec') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Sweetened Ginger') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('grand marnier') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('bourbon') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('simple syrup') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Peche') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Sugar') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('creme de violette') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('chocolate bitters') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('blackberry brandy / cassis') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lemon, 25ml sugar syrup, 50ml gin, top soda') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dash Absinthe') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dash orange') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Top champs') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('top soda') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Fernet branca') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('beefeater gin') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lime wedges') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Haydens mix') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('– 20ml lemon, 20ml sugar syrup, 50ml gin, 2 dash ango') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('ango') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lime, 20ml honey syrup, 50ml light rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Cacao') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('ginger syrup') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Jamaican rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('light rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Champagne') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('rye, 15ml dry vermouth, 7.5ml picon, 7.5ml maraschino') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Port Tawny') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('pey') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dash Absinte') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('fino sherry') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('orange Bitters') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dry/bianco vermouth') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Sweetened ginger juice') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Jamaican Rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('cachaca') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('cacao') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Benedictine') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('falernum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dry curaçao') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dry curacau') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dash orange') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Creme de Menthe') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Aged rum (S&C)') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('marachino') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dash absinthe') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Maraschino') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('White rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('cut honey') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('honey syrup') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Lemon') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('agave') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('lemon, 25ml bianco vermouth, 25ml curacao, 25ml cognac') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Egg white') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('white rum') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dash bitters') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Gin, 25ml Sweet Vermouth, 25ml Dry Vermouth') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Tequila') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Licor 43') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Creme de Cassis') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Amaretto, 45ml Scotch') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Fresh Lime Juice') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('vodka') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Orange wedge') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('kümmel') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Orange') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('dry triple sec') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dash absinthe') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('Dom Benedictine') ON CONFLICT (name) DO NOTHING;
INSERT INTO ingredients (name) VALUES ('grenadine') ON CONFLICT (name) DO NOTHING;
