import { Bullets, LegalPage, LegalSection, P, SupportEmail } from '@/components/legal/LegalPage';
import { BRAND } from '@/constants/brand';

export default function Terms() {
  return (
    <LegalPage title="Terms of use">
      <P>
        These terms cover your use of {BRAND.productName}, operated by {BRAND.operator} (&quot;we&quot;). By creating an
        account or using the app you agree to them.
      </P>

      <LegalSection heading="Who can use it">
        <P>
          You must be of legal drinking age where you live, and at least 18. Venue admins decide who joins their venue and
          what role each member has, and are responsible for their members&apos; use of the venue.
        </P>
      </LegalSection>

      <LegalSection heading="Your content">
        <P>
          You keep ownership of what you create. You let us store, copy and display it as needed to run the service for
          you and your venue. Content created in a venue belongs to that venue and stays with it if you leave. Only upload
          photos, logos and recipes you have the right to use.
        </P>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <Bullets
          items={[
            'Don’t use the service for anything illegal, harmful or abusive.',
            'Don’t try to access venues or accounts that aren’t yours, or to test or bypass our security.',
            'Don’t scrape, overload or disrupt the service.',
          ]}
        />
      </LegalSection>

      <LegalSection heading="AI features and recipes">
        <P>
          Illustrations and glassware suggestions are generated by AI and may be inaccurate. Recipes are for
          professional use: follow your local laws and responsible-service-of-alcohol rules.
        </P>
      </LegalSection>

      <LegalSection heading="The service">
        <P>
          We work to keep {BRAND.productName} available and your data safe, but the service is provided &quot;as is&quot;
          without warranties. We may change features or stop offering the service; if we stop, we will give reasonable
          notice so venues can export their content. To the extent the law allows, we are not liable for indirect or
          consequential losses, or for losses caused by content that members add.
        </P>
      </LegalSection>

      <LegalSection heading="Ending your account">
        <P>
          You can delete your account at any time from Settings → Account → Delete account. We may suspend accounts that
          break these terms.
        </P>
      </LegalSection>

      <LegalSection heading="Changes and contact">
        <P>
          We will update the date above when these terms change, and tell you in the app about significant changes.
          Questions: <SupportEmail />.
        </P>
      </LegalSection>
    </LegalPage>
  );
}
