import { useColorScheme } from "@/hooks/use-color-scheme";
import { BottomTabBarProps } from "@react-navigation/bottom-tabs";
import { PlatformPressable } from "@react-navigation/elements";
import { useLinkBuilder } from "@react-navigation/native";
import { LinearGradient } from "expo-linear-gradient";
import { StyleSheet, View } from "react-native";

export function LiquidTabBar({
    state,
    descriptors,
    navigation,
}: BottomTabBarProps) {
    const { buildHref } = useLinkBuilder();
    const colorScheme = useColorScheme();
    
    // Minimalist dark theme for the tab bar icons
    const activeColor = "#FFFFFF";
    const inactiveColor = "rgba(255, 255, 255, 0.4)";

    // Check if the current tab should be hidden
    const currentRouteKey = state.routes[state.index].key;
    const currentOptions = descriptors[currentRouteKey].options as any;
    
    if (currentOptions?.tabBarStyle?.display === "none") {
        return null;
    }

    return (
        <View style={styles.container}>
            <LinearGradient
                colors={['transparent', '#000000']}
                locations={[0, 1]}
                style={styles.gradientFade}
            />
            <View style={styles.solidBackground}>
                <View style={styles.tabBar}>
                    {(() => {
                        // We use `state.routes` as the source of truth for the tabs order and rendering
                        // Exclude any routes where the tab bar is explicitly hidden
                        const validRoutes = state.routes.filter(route => {
                            const { options } = descriptors[route.key];
                            // Exclude tabs explicitly set to not display
                            if ((options as any)?.tabBarStyle?.display === "none") {
                                return false;
                            }
                            // Exclude deep nested routes often generated by Expo Router if they shouldn't show up here
                            // In most cases, standard tabs defined in _layout.tsx are top-level index names 
                            // or the main name. We can just rely on state.routes that 
                            // have an icon defined in options since layout screens define them.
                            if (!options.tabBarIcon && !options.tabBarLabel && !options.title) {
                                return false; // Hide tabs that don't have basic tab bar properties configured
                            }
                            return true;
                        });

                        return validRoutes.map((route, routeIndex) => {
                            const { options } = descriptors[route.key];
                            
                            // The true state.index might be different than our custom mapped index.
                            // state.index refers to the raw state.routes array.
                            const originalIndex = state.routes.findIndex(r => r.key === route.key);
                            const isFocused = state.index === originalIndex;

                            const onPress = () => {
                                const event = navigation.emit({
                                    type: "tabPress",
                                    target: route.key,
                                    canPreventDefault: true,
                                });

                                if (!isFocused && !event.defaultPrevented) {
                                    navigation.navigate(route.name, route.params);
                                }
                            };

                            const onLongPress = () => {
                                navigation.emit({
                                    type: "tabLongPress",
                                    target: route.key,
                                });
                            };

                            return (
                                <PlatformPressable
                                    key={route.key}
                                    href={buildHref(route.name, route.params)}
                                    accessibilityState={isFocused ? { selected: true } : {}}
                                    accessibilityLabel={options.tabBarAccessibilityLabel}
                                    testID={options.tabBarButtonTestID}
                                    onPress={onPress}
                                    onLongPress={onLongPress}
                                    style={styles.tabItem}
                                >
                                    {options.tabBarIcon && options.tabBarIcon({
                                        focused: isFocused,
                                        color: isFocused ? activeColor : inactiveColor,
                                        size: 28,
                                    })}
                                </PlatformPressable>
                            );
                        });
                    })()}
                </View>
            </View>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        zIndex: 100,
    },
    gradientFade: {
        width: "100%",
        height: 60, // How tall the fade effect is above the solid black
    },
    solidBackground: {
        backgroundColor: '#000000',
        width: "100%",
    },
    tabBar: {
        flexDirection: "row",
        justifyContent: "space-around", // Distribute spacing evenly around items
        alignItems: "center",
        paddingBottom: 35, // Safe area / bottom spacing
        paddingHorizontal: 10, // Reduce padding to allow more spacing room
    },
    tabItem: {
        alignItems: "center",
        justifyContent: "center",
        height: 50,
        width: 44, // Fixed tap width instead of flex: 1 for perfectly even centering
    },
});
