-- Instagram and other social accounts for the bars on the app, so each bar
-- page links them. Found on 6 Oct 2026: links on each bar's own website first,
-- then search where a bar has no site or its site is a hotel's or group's.
-- Only a bar's own accounts: a hotel bar with no account of its own gets
-- none rather than the hotel's.
-- Fills only what's empty, so a value an owner set is kept. A handle that
-- isn't on this stack (bars added by hand in production) is skipped.

UPDATE "public"."profiles" AS p
SET "instagram" = coalesce(p.instagram, v.instagram),
    "social_links" = coalesce(p.social_links, v.social_links)
FROM (VALUES
    ('14delarosa', '14delarosa', NULL::text[]),
    ('1661bar', '1661bar', ARRAY['https://www.facebook.com/bar1661/']),
    ('1862drybar', '1862drybar', NULL::text[]),
    ('1930cocktailbar', '1930cocktailbar', NULL::text[]),
    ('28hongkongstreet', '28hongkongstreet', ARRAY['https://www.facebook.com/28hongkongstreet/']),
    ('3monosbar', '3monosbar', NULL::text[]),
    ('69colebrookerow', '69colebrookerow', NULL::text[]),
    ('abarwithshapesforaname', 'a_bar_with_shapes_for_a_name_', NULL::text[]),
    ('aboveboardbarmelb', 'aboveboardbarmelb', ARRAY['https://www.facebook.com/aboveboardbar/']),
    ('abvsf', 'abvsf', NULL::text[]),
    ('alice_cheongdam', 'alice_cheongdam', NULL::text[]),
    ('allegory_dc', 'allegory_dc', NULL::text[]),
    ('alma__prague', 'alma__prague', ARRAY['https://www.facebook.com/almaprague/']),
    ('alquimicocartagena', 'alquimicocartagena', NULL::text[]),
    ('amarobarlondon', 'amarobarlondon', NULL::text[]),
    ('amoryamargo', 'amoryamargo', ARRAY['https://www.facebook.com/amoryamargony/']),
    ('andy_wahloo', 'andy_wahloo', NULL::text[]),
    ('angelssharenyc', 'angelssharenyc', NULL::text[]),
    ('antiqueamericanbar_bratislava', 'antiqueamericanbar_bratislava', NULL::text[]),
    ('anvilhouston', 'anvilhouston', ARRAY['https://www.facebook.com/anvilhouston/', 'https://x.com/anvilhouston']),
    ('apolloinn.bar', 'apolloinn.bar', NULL::text[]),
    ('apolloniabar', 'apolloniabar', ARRAY['https://www.facebook.com/apolloniabar/']),
    ('aquabarbangkok', 'aquabarbangkok', ARRAY['https://www.facebook.com/aquabarbangkok/']),
    ('arcatulum', 'arcatulum', ARRAY['https://www.facebook.com/arcatulum/']),
    ('argobarhk', 'argobarhk', NULL::text[]),
    ('artesianbar', 'artesianbarlondon', ARRAY['https://www.facebook.com/artesianbar/']),
    ('atlasbarsg', 'atlasbarsg', ARRAY['https://www.facebook.com/atlasbarsingapore/']),
    ('attaboy134', 'attaboy134', NULL::text[]),
    ('aviarycocktails', 'aviarycocktails', NULL::text[]),
    ('baba_au_rum', 'baba_au_rum', NULL::text[]),
    ('baccanoroma', 'baccanoroma', ARRAY['https://www.facebook.com/ristorantebaccano/']),
    ('backdoorbodega', 'backdoorbodega', ARRAY['https://www.facebook.com/backdoorbodega/']),
    ('baltrabar', 'baltrabar', ARRAY['https://www.facebook.com/baltrabar/']),
    ('bandistahouston', 'bandistahouston', NULL::text[]),
    ('bar.bellamy', 'bar.bellamy', NULL::text[]),
    ('bar.cham', 'bar.cham', NULL::text[]),
    ('bar.us.bkk', 'bar.us.bkk', NULL::text[]),
    ('bar1806', 'bar1806', ARRAY['https://www.facebook.com/bar1806melbourne/']),
    ('bar_raval', 'bar_raval', NULL::text[]),
    ('bar_trench', 'bar_trench', ARRAY['https://www.facebook.com/bartrench/']),
    ('barcockmad', 'barcockmad', ARRAY['https://x.com/barcockmadrid']),
    ('bargabriel.ist', 'bargabriel.ist', NULL::text[]),
    ('bargenyamamoto', 'bar_gen_yamamoto', NULL::text[]),
    ('barglue', 'barglue', NULL::text[]),
    ('bargoto_nyc', 'bargoto_nyc', NULL::text[]),
    ('barhighfive', 'barhighfive', ARRAY['https://www.facebook.com/barhighfive/', 'https://x.com/barhighfive']),
    ('barkumiko', 'barkumiko', NULL::text[]),
    ('barleatherapron', 'barleatherapron', ARRAY['https://www.facebook.com/barleatherapron/', 'https://x.com/barleatherapron']),
    ('barlelion', 'barlelion', NULL::text[]),
    ('barleonehk', 'barleonehk', NULL::text[]),
    ('barlibre_ikebukuro', 'barlibre_ikebukuro', NULL::text[]),
    ('barmadonnabk', 'barmadonnabk', NULL::text[]),
    ('barmauromx', 'barmauromx', NULL::text[]),
    ('barmood_taipei', 'barmood_taipei', NULL::text[]),
    ('barnouveau', 'bar_nouveau_', NULL::text[]),
    ('barorchardginza', 'barorchardginza', NULL::text[]),
    ('barplanetbar', 'barplanetbar', NULL::text[]),
    ('barpompette_to', 'barpompette_to', NULL::text[]),
    ('barronegroathens', 'barronegroathens', ARRAY['https://www.facebook.com/barronegroathens/']),
    ('barsathorn', 'barsathorn', ARRAY['https://www.facebook.com/barsathorn/']),
    ('barsnack.nyc', 'barsnack.nyc', NULL::text[]),
    ('barspiritforward.blr', 'barspiritforward.blr', NULL::text[]),
    ('barthreelondon', 'barthreelondon', NULL::text[]),
    ('bartilda.sydney', 'bartilda.sydney', NULL::text[]),
    ('bartrigona', 'bartrigona', NULL::text[]),
    ('bekeb_sma', 'bekeb_sma', ARRAY['https://www.facebook.com/bekebartisanalmixology/']),
    ('bellboy.tlv', 'bellboy.tlv', ARRAY['https://www.facebook.com/bellboy.bar/']),
    ('belowstairsbar', 'belowstairsbar', NULL::text[]),
    ('bemelmansbar', 'bemelmansbar', NULL::text[]),
    ('benfiddich_tokyo', 'benfiddich_tokyo', ARRAY['https://www.facebook.com/barbenfiddich/', 'https://x.com/bar_benfiddich']),
    ('bird.cph', 'bird.cph', NULL::text[]),
    ('bisouschicago', 'bisouschicago', NULL::text[]),
    ('bkksocialclub', 'bkksocialclub', NULL::text[]),
    ('blackpearlfitzroy', 'blackpearlfitzroy', ARRAY['https://www.facebook.com/blackpearlfitzroy/']),
    ('blackrockbars', NULL, ARRAY['https://www.facebook.com/barblackrock/']),
    ('blinkerbar', 'blinkerbar', NULL::text[]),
    ('boadascocktails', 'boadascocktails', ARRAY['https://www.facebook.com/boadascocktails/']),
    ('boilermaker.goa', 'boilermaker.goa', NULL::text[]),
    ('bonvedinburgh', 'bonvedinburgh', NULL::text[]),
    ('bonvivantsbahamas', 'bonvivantsbahamas', ARRAY['https://www.facebook.com/bonvivantsbs/']),
    ('bop_bartendersofpony', 'bop_bartendersofpony', NULL::text[]),
    ('botanistdining', 'botanistdining', ARRAY['https://www.facebook.com/botanistdining/']),
    ('bramble_bar', 'bramble_bar', NULL::text[]),
    ('brokenshaker', 'brokenshaker', NULL::text[]),
    ('brujasmex', 'brujasmex', NULL::text[]),
    ('bryantslounge', 'bryantslounge', ARRAY['https://www.facebook.com/bryantscocktaillounge/']),
    ('byrdimelb', 'byrdimelb', ARRAY['https://www.facebook.com/byrdimelb/']),
    ('cafelatrovamiami', 'cafelatrovamiami', ARRAY['https://www.facebook.com/cafelatrovamiami/']),
    ('cahootslondon', 'cahootslondon', ARRAY['https://www.tiktok.com/@cahootslondon', 'https://www.facebook.com/cahootslondon/']),
    ('calloohcallaybar', 'calloohcallaybar', ARRAY['https://www.facebook.com/calloohcallaylondon/', 'https://x.com/callooh_callay']),
    ('camparinoingalleria', 'camparinoingalleria', ARRAY['https://www.facebook.com/camparinoingalleria/']),
    ('candelariaparis', 'candelariaparis', NULL::text[]),
    ('canonseattle', 'canonseattle', ARRAY['https://www.facebook.com/canonseattle/', 'https://www.threads.com/@canonseattle']),
    ('cantina.ok', 'cantina.ok', NULL::text[]),
    ('caretakers.cottage', 'caretakers.cottage', NULL::text[]),
    ('carnavalbar', 'carnavalbar', ARRAY['https://www.facebook.com/carnavalbarlima/']),
    ('carrots.jakarta', 'carrots.jakarta', NULL::text[]),
    ('catbiteclub', 'catbiteclub', NULL::text[]),
    ('causeeffectcpt', 'causeeffectbar', NULL::text[]),
    ('central.station', 'central.station', ARRAY['https://www.facebook.com/centralstationbeirut/']),
    ('centurygrandphx', 'centurygrandphx', ARRAY['https://www.tiktok.com/@centurygrandphx', 'https://www.facebook.com/centurygrandphx/']),
    ('chainayateandcocktails', 'chainayateandcocktails', ARRAY['https://www.facebook.com/chainayabar/']),
    ('civlibto', 'civlibto', NULL::text[]),
    ('civwrksto', 'civwrksto', NULL::text[]),
    ('cleaverlv', 'cleaverlv', ARRAY['https://www.facebook.com/cleaverlasvegas/']),
    ('cloverclubny', 'cloverclubny', ARRAY['https://www.facebook.com/cloverclubny/']),
    ('clydecommon', 'clydecommon', NULL::text[]),
    ('cmyk.china', 'cmyk.china', NULL::text[]),
    ('coahongkong', 'coahongkong', ARRAY['https://www.facebook.com/coahongkong/']),
    ('cobracolumbus', 'cobracolumbus', NULL::text[]),
    ('cochinchina.bar', 'cochinchina.bar', NULL::text[]),
    ('columbiaroom', 'columbiaroom', NULL::text[]),
    ('comperelapin', 'comperelapin', NULL::text[]),
    ('copperbay_paris', 'copperbay_paris', ARRAY['https://www.facebook.com/copperbayparis/']),
    ('cosmopony.jkt', 'cosmopony.jkt', NULL::text[]),
    ('couchstirchleyb30', 'couchstirchleyb30', NULL::text[]),
    ('cravanparis', 'cravanparis', NULL::text[]),
    ('crazypedros', 'crazypedros', ARRAY['https://www.facebook.com/crazypedros/']),
    ('curenola', 'curenola', NULL::text[]),
    ('d.bespoke', 'd.bespoke', ARRAY['https://www.facebook.com/dbespoke/']),
    ('daisy.losangeles', 'daisy.losangeles', NULL::text[]),
    ('danicoparis', 'danicoparis', NULL::text[]),
    ('dantenewyorkcity', 'dantenewyorkcity', ARRAY['https://www.facebook.com/dantenewyorkcity/']),
    ('darksidehk', 'darksidebar', NULL::text[]),
    ('dead.end.paradise', 'dead.end.paradise', NULL::text[]),
    ('deadwax.enmore', 'deadwax.enmore', NULL::text[]),
    ('deanandnancyon22', 'deanandnancyon22', NULL::text[]),
    ('dearirving', 'dearirving', NULL::text[]),
    ('deathandcompany', 'deathandcompany', ARRAY['https://www.facebook.com/deathandcompany/']),
    ('deathandcompany.la', 'deathandcompany', ARRAY['https://www.facebook.com/deathandcompany/']),
    ('devie.bar', 'devie.bar', NULL::text[]),
    ('devilscut.madrid', 'devilscut.madrid', NULL::text[]),
    ('dirtydickparis', 'dirtydickparis', NULL::text[]),
    ('disco_pantera', 'bartigra', NULL::text[]),
    ('doublechickenpleasenyc', 'doublechickenpleasenyc', NULL::text[]),
    ('dr.stravinsky_bcn', 'dr.stravinsky_bcn', ARRAY['https://www.facebook.com/drstravinskybcn/']),
    ('draftland', 'draftland', ARRAY['https://www.facebook.com/draftland/']),
    ('drinkkongbar', 'drinkkongbar', ARRAY['https://www.facebook.com/drinkkong/']),
    ('drinkmanolo', 'drinkmanolo', NULL::text[]),
    ('drymartinibarcelona', 'drymartinibarcelona', NULL::text[]),
    ('drywavecocktailstudio', 'drywavecocktailstudio', NULL::text[]),
    ('dunlin.bar', 'dunlin.bar', ARRAY['https://www.facebook.com/dunlin.bar/']),
    ('elbaroncafe', 'elbaroncafe', ARRAY['https://www.facebook.com/elbaroncafeandcocktailbar/']),
    ('elcopitasbar', 'elcopitasbar', NULL::text[]),
    ('elephantroomsg', 'elephantroomsg', ARRAY['https://www.facebook.com/elephantroomsg/']),
    ('elevenmadisonpark', 'elevenmadisonpark', NULL::text[]),
    ('elgalloaltanero', 'elgalloaltanero', NULL::text[]),
    ('employeesonlyny', 'employeesonlyny', ARRAY['https://www.facebook.com/employeesonlynyc/']),
    ('eximiabar', 'eximiabar', NULL::text[]),
    ('experimentalcocktailclub', 'experimentalcocktailclub', NULL::text[]),
    ('fancycocktailbar', 'fancycocktailbar', ARRAY['https://www.facebook.com/bestintentionsbar/']),
    ('fiftymils', 'fiftymils', NULL::text[]),
    ('filthyxiii', 'filthyxiii', NULL::text[]),
    ('floreriaatlantico', 'floreriaatlantico', NULL::text[]),
    ('floridita_cuba', NULL, ARRAY['https://www.facebook.com/barfloriditahavana/']),
    ('flyingdutchmencocktails', 'flyingdutchmencocktails', ARRAY['https://www.facebook.com/flyingdutchmencocktails/']),
    ('foco.bcn', 'foco.bcn', NULL::text[]),
    ('fomabar.mx', 'fomabar.mx', NULL::text[]),
    ('forbina_bar', 'forbina_bar', NULL::text[]),
    ('freniefrizioni', 'freniefrizioni', NULL::text[]),
    ('frequenceparis', 'frequenceparis', NULL::text[]),
    ('frontbackaccra', 'frontbackaccra', ARRAY['https://www.facebook.com/frontbackaccra/', 'https://x.com/frontbackaccra']),
    ('fura.sg', 'fura.sg', NULL::text[]),
    ('galaxybardxb', 'galaxybardxb', ARRAY['https://x.com/galaxybardxb', 'https://www.youtube.com/channel/UCzbIHCKuVkq1pRVu16T41fQ']),
    ('gibsonbarsg', 'gibsonbarsg', ARRAY['https://www.facebook.com/gibsonbarsg/']),
    ('gimlet.melbourne', 'gimlet.melbourne', NULL::text[]),
    ('ginpalacemelb', 'ginpalacemelb', ARRAY['https://www.facebook.com/ginpalacemelbourne/']),
    ('god_bkk', 'god_bkk', NULL::text[]),
    ('gokan.hk', 'gokan.hk', NULL::text[]),
    ('goodwater.melbourne', 'goodwater.melbourne', NULL::text[]),
    ('gorillabarskg', 'gorillabarskg', ARRAY['https://www.facebook.com/gorillabarskg/']),
    ('guilhotinabar', 'guilhotinabar', NULL::text[]),
    ('gunghobar', 'gunghobar', NULL::text[]),
    ('gus_sipanddip', 'gus_sipanddip', ARRAY['https://www.facebook.com/gussipanddip/']),
    ('hachabar', 'hachabar', NULL::text[]),
    ('handsdownmelbourne', 'handsdownmelbourne', NULL::text[]),
    ('handshake_bar', 'handshake_bar', NULL::text[]),
    ('hankypankydf', 'hankypankydf', NULL::text[]),
    ('happiness_hoxton', 'happiness_hoxton', NULL::text[]),
    ('happyaccidentsbar', 'happyaccidentsbar', ARRAY['https://www.tiktok.com/@happyaccidentsbar']),
    ('harrison.bsas', 'harrison.bsas', NULL::text[]),
    ('harrysbar_theoriginal', 'harrysbar_theoriginal', ARRAY['https://www.facebook.com/HarrysBarParis/']),
    ('hawksmoorrestaurants', 'hawksmoorrestaurants', ARRAY['https://www.facebook.com/hawksmoor/', 'https://x.com/hawksmoortweets', 'https://www.youtube.com/@hawksmoor']),
    ('herbsandrye', 'herbsandrye', ARRAY['https://www.facebook.com/herbsandrye/']),
    ('hero_nairobi', 'hero_nairobi', ARRAY['https://www.facebook.com/herorestaurantke/']),
    ('heylovepdx', 'heylovepdx', ARRAY['https://www.facebook.com/heylovepdx/']),
    ('heypalu', 'heypalu', ARRAY['https://www.facebook.com/heypalu/']),
    ('hideout_bath', 'hideout_bath', NULL::text[]),
    ('himkok.oslo', 'himkok.oslo', ARRAY['https://www.facebook.com/himkok.oslo/']),
    ('hopeandsesame', 'hopeandsesame', NULL::text[]),
    ('hudsonroomshanoi', 'hudsonroomshanoi', NULL::text[]),
    ('identidadcocktailbar', 'identidadcocktailbar', NULL::text[]),
    ('indulgebistro', NULL, ARRAY['https://www.facebook.com/indulgebistrotaipei/']),
    ('infinitybeyond_tw', 'infinitybeyond_tw', NULL::text[]),
    ('insider.bar.lab', 'insider.bar.lab', NULL::text[]),
    ('jackroseindc', 'jackroseindc', ARRAY['https://www.facebook.com/jackroseindc/']),
    ('jerrythomas.speakeasy', 'jerrythomas.speakeasy', NULL::text[]),
    ('jewelnola', 'jewelnola', ARRAY['https://www.facebook.com/jewelofthesouthnola/']),
    ('jiggerandponysg', 'jiggerandponysg', ARRAY['https://www.facebook.com/jiggerandpony/']),
    ('julephou', 'julephou', ARRAY['https://www.facebook.com/julephou/']),
    ('juneoncambie', 'juneoncambie', NULL::text[]),
    ('kaitodelvalle', 'kaitodelvalle', NULL::text[]),
    ('katanakitten_nyc', 'katanakitten_nyc', ARRAY['https://www.facebook.com/katanakittennyc/']),
    ('keenssteakhouse', 'keenssteakhouse', ARRAY['https://www.facebook.com/keenssteakhouse/']),
    ('kikis.lounge', 'kikis.lounge', ARRAY['https://www.tiktok.com/@kikis.lounge', 'https://www.facebook.com/kikis.tikilounge/']),
    ('kinsman.hk', 'kinsman.hk', NULL::text[]),
    ('kwantmayfair', 'kwantmayfair', NULL::text[]),
    ('lab22cardiff', 'lab22cardiff', ARRAY['https://www.facebook.com/lab22cardiff/', 'https://x.com/lab22cardiff']),
    ('ladybee.lima', 'ladybee.lima', NULL::text[]),
    ('lafactoriapr', 'lafactoriapr', ARRAY['https://www.tiktok.com/@lafactopr', 'https://www.facebook.com/lafactoriapr/']),
    ('lair.newdelhi', 'lair.newdelhi', ARRAY['https://www.facebook.com/lairdelhi/']),
    ('lamp.bar', 'lamp.bar', NULL::text[]),
    ('lantiquario_napoli', 'lantiquario_napoli', NULL::text[]),
    ('latebloomers.zurich', 'latebloomers.zurich', ARRAY['https://www.facebook.com/latebloomersthebar/']),
    ('le_chamber', 'le_chamber', NULL::text[]),
    ('le_parfum_montpellier', 'le_parfum_montpellier', ARRAY['https://www.facebook.com/leparfummontpellier/']),
    ('lemaryceleste', 'lemaryceleste', NULL::text[]),
    ('lennons.bkk', 'lennons.bkk', NULL::text[]),
    ('lesyndicat', 'lesyndicat', NULL::text[]),
    ('librarybartoronto', 'librarybartoronto', ARRAY['https://www.facebook.com/librarybarryh/']),
    ('librarybytheseagc', 'librarybytheseagc', NULL::text[]),
    ('limantourmx', 'limantourmx', ARRAY['https://www.facebook.com/limantourmx/']),
    ('line.athens', 'line.athens', ARRAY['https://www.facebook.com/line.athens/']),
    ('little_rituals_bar', 'little_rituals_bar', ARRAY['https://www.facebook.com/littleritualsbar/', 'https://x.com/lrituals']),
    ('littlereddoor_paris', 'littlereddoor_paris', ARRAY['https://www.facebook.com/lrdparis/', 'https://www.youtube.com/@littlereddoorparis']),
    ('localefirenze', 'localefirenze', ARRAY['https://www.facebook.com/localefirenze/']),
    ('loma_bar', 'loma_bar', NULL::text[]),
    ('longbarsg', 'longbarsg', ARRAY['https://www.facebook.com/longbarsg/']),
    ('lostandfounddrinkery', 'lostandfounddrinkery', NULL::text[]),
    ('lpmdubai', 'lpmdubai', NULL::text[]),
    ('lucysstockholm', 'lucysstockholm', ARRAY['https://www.facebook.com/lucysstockholm/']),
    ('lyanessbar', 'lyanessbar', ARRAY['https://www.facebook.com/lyanessbar/']),
    ('macebarnyc', 'macebarnyc', NULL::text[]),
    ('madridangelita', 'madridangelita', ARRAY['https://www.facebook.com/madridangelita/', 'https://x.com/madrid_angelita']),
    ('mahaniyom.cocktailbar', 'mahaniyom.cocktailbar', NULL::text[]),
    ('maisonpremiere', 'maisonpremiere', NULL::text[]),
    ('mambanegra.22', 'mambanegra.22', NULL::text[]),
    ('manhattan_sg', 'manhattan_sg', NULL::text[]),
    ('martinys_nyc', 'martinys_nyc', NULL::text[]),
    ('maybe_sammy_sydney', 'maybe_sammy_sydney', ARRAY['https://www.facebook.com/maybesammysydney/']),
    ('mecenasbar', 'mecenasbar', ARRAY['https://www.tiktok.com/@mecenasbar']),
    ('mimikakushi', 'mimikakushi', ARRAY['https://www.facebook.com/p/Mimi-Kakushi-100064251456210/']),
    ('mirate.losangeles', 'mirate.losangeles', NULL::text[]),
    ('mirrorbarcarlton', 'mirrorbarcarlton', ARRAY['https://www.facebook.com/MirrorBarCarlton/', 'https://www.youtube.com/@mirrorbar8181']),
    ('mius.hongkong', 'mius.hongkong', NULL::text[]),
    ('mms_maltmixologyspace', 'mms_maltmixologyspace', NULL::text[]),
    ('mobarsg', 'mobarsg', ARRAY['https://www.facebook.com/MOBARSG/']),
    ('mobarshenzhen', 'mobarshenzhen', NULL::text[]),
    ('modernhausjkt', 'modernhausjkt', NULL::text[]),
    ('moebiusmilano', 'moebiusmilano', ARRAY['https://www.facebook.com/moebiusmilano/']),
    ('montanabarhk', 'montanabarhk', NULL::text[]),
    ('mothercocktailbar', 'mothercocktailbar', ARRAY['https://www.tiktok.com/@mothercocktailbar', 'https://www.facebook.com/mothercocktails/']),
    ('mr.hoots', 'mr.hoots', NULL::text[]),
    ('mrfoggsgb', NULL, ARRAY['https://www.facebook.com/MrFoggsResidence/']),
    ('naked.athens', 'naked.athens', ARRAY['https://www.tiktok.com/@naked.ath', 'https://www.facebook.com/naked.athens/']),
    ('napoleonhousenola', 'napoleonhousenola', ARRAY['https://www.facebook.com/napoleonhousenola/']),
    ('nativebarsg', 'nativebarsg', ARRAY['https://www.facebook.com/nativebarsg/']),
    ('navystrengthseattle', 'navystrengthseattle', NULL::text[]),
    ('night.hawk.sg', 'night.hawk.sg', NULL::text[]),
    ('nightjar', 'nightjar', ARRAY['https://www.tiktok.com/@nightjarbar', 'https://www.facebook.com/barnightjar/']),
    ('nosleepclubsg', 'nosleepclubsg', NULL::text[]),
    ('nouvellevague_tirana', 'nouvellevague_tirana', ARRAY['https://www.facebook.com/cocktailbartirana/']),
    ('nuloungebar', 'nuloungebar', ARRAY['https://www.tiktok.com/@nuloungebar', 'https://www.facebook.com/nuloungebar/']),
    ('nutmegandclove', 'nutmegandclove', NULL::text[]),
    ('obsidianbar_sz', 'obsidianbar_sz', NULL::text[]),
    ('officialcafepacifico', 'officialcafepacifico', ARRAY['https://www.facebook.com/cafepacificolondon/', 'https://x.com/cafe_pacifico']),
    ('officina_milano', 'officina_milano', NULL::text[]),
    ('offtrack.sg', 'offtrack.sg', NULL::text[]),
    ('oldlovessyd', 'oldlovessyd', ARRAY['https://www.facebook.com/oldlovessyd/']),
    ('oldmatesplace', 'oldmatesplace', ARRAY['https://www.facebook.com/oldmatesplace/']),
    ('opm.bkk', 'opm.bkk', ARRAY['https://www.facebook.com/opiumbarbkk/']),
    ('originbarsg', 'originbarsg', ARRAY['https://www.facebook.com/originbarsg/']),
    ('otro___bar', 'otro___bar', NULL::text[]),
    ('overstory', 'overstory', NULL::text[]),
    ('p_u_b_l_i_c', 'p_u_b_l_i_c_', ARRAY['https://www.facebook.com/publicpublicpublic/', 'https://x.com/p_u_b_l_i_c_']),
    ('pandaandsons', 'pandaandsons', ARRAY['https://www.facebook.com/pandaandsons/']),
    ('paradiso_barcelona', 'paradiso_barcelona', ARRAY['https://www.facebook.com/paradisobarcelona/']),
    ('passingfancies.bar', 'passingfancies.bar', NULL::text[]),
    ('pch_sf', 'pch_sf', ARRAY['https://www.facebook.com/pchsf/']),
    ('pdtnyc', 'pdtnyc', ARRAY['https://www.facebook.com/pdtcocktails/']),
    ('pendant.publicbar', 'pendant.publicbar', NULL::text[]),
    ('penicillin_bar', 'penicillin_bar', ARRAY['https://www.facebook.com/penicillinbar/']),
    ('penrose.kl', 'penrose.kl', NULL::text[]),
    ('ponyupshanghai', 'ponyupshanghai', NULL::text[]),
    ('potatoheadbali', 'potatoheadbali', ARRAY['https://www.facebook.com/potatoheadbali/', 'https://www.youtube.com/channel/UCMms6Vm88v3Kll9Rrj5Bahg']),
    ('presidentebar', 'presidentebar', ARRAY['https://www.facebook.com/presidentebar/', 'https://x.com/bar_presidente']),
    ('pressclubcocktailbar', 'pressclubcocktailbar', NULL::text[]),
    ('problemchild_ph', 'problemchild_ph', NULL::text[]),
    ('prophecybar', 'prophecybar', NULL::text[]),
    ('quinaryhk', 'quinaryhk', ARRAY['https://www.facebook.com/quinaryhk/']),
    ('rabbitholebkk', 'rabbitholebkk', ARRAY['https://www.facebook.com/rabbitholebkk/']),
    ('ramblinrascaltavern', 'ramblinrascaltavern', NULL::text[]),
    ('rattlebag.belfast', 'rattlebag.belfast', NULL::text[]),
    ('rayocdmx', 'rayocdmx', NULL::text[]),
    ('redfrogspeakeasy', 'redfrogspeakeasy', ARRAY['https://www.facebook.com/redfrogspeakeasy/', 'https://x.com/redfrogspky']),
    ('republicbarsg', 'republicbarsg', NULL::text[]),
    ('ritacocktails', 'ritacocktails', ARRAY['https://www.facebook.com/ritacocktails/']),
    ('rodahusetsthlm', 'rodahusetsthlm', ARRAY['https://www.facebook.com/rodahusetsthlm/']),
    ('rubycph', 'rubycph', ARRAY['https://www.facebook.com/rubycph/']),
    ('sagerandwilde', 'sagerandwilde', ARRAY['https://www.tiktok.com/@sagerandwilde']),
    ('sagohouse.sg', 'sagohouse.sg', ARRAY['https://www.tiktok.com/@sagohouse.sg']),
    ('salmonguru', 'salmonguru', ARRAY['https://www.facebook.com/salmonguru/']),
    ('sastreriamartinezlima', 'sastreriamartinezlima', ARRAY['https://www.facebook.com/sastreriamartinezlima/']),
    ('satans_whiskers', 'satans_whiskers', ARRAY['https://x.com/satans_whiskers']),
    ('savasbarmad', 'savasbarmad', NULL::text[]),
    ('saxonandparole', 'saxonandparole', NULL::text[]),
    ('scarfesbar', 'scarfesbar', ARRAY['https://www.facebook.com/scarfesbar/', 'https://x.com/scarfesbar']),
    ('schmuck.ny', 'schmuckordie', NULL::text[]),
    ('schofields.bar', 'schofields.bar', ARRAY['https://www.facebook.com/schofields.bar/']),
    ('schumanns_house', NULL, ARRAY['https://www.facebook.com/schumanns.hofgarten/']),
    ('scotchlodge', 'scotchlodge', ARRAY['https://www.facebook.com/scotchlodge/']),
    ('selvaoaxaca', 'selvaoaxaca', NULL::text[]),
    ('servicebardc', 'servicebardc', ARRAY['https://www.facebook.com/servicebardc/', 'https://x.com/servicebardc']),
    ('sexyfishlondon', 'sexyfishlondon', ARRAY['https://www.facebook.com/sexyfishlondon/']),
    ('sidecarindia', 'sidecarindia', NULL::text[]),
    ('sidedoor_sg', 'sidedoor_sg', NULL::text[]),
    ('sietenegronis', 'sietenegronis', NULL::text[]),
    ('sin_tax_bar', 'sin_tax_bar', ARRAY['https://www.facebook.com/sinandtax/']),
    ('sipandguzzlenyc', 'sipandguzzlenyc', NULL::text[]),
    ('sips.barcelona', 'sips.barcelona', NULL::text[]),
    ('smokeandbitters', 'smoke.bitters', ARRAY['https://www.facebook.com/smokeandbitters/']),
    ('smugglerscovesf', 'smugglerscovesf', ARRAY['https://www.facebook.com/smugglerscovesf/']),
    ('sober_company', 'sober_company', ARRAY['https://www.facebook.com/sobercompany/']),
    ('speaklow_shanghai', 'speaklow_shanghai', NULL::text[]),
    ('star__bar', 'star__bar', NULL::text[]),
    ('subastor', 'subastor', ARRAY['https://www.youtube.com/@subastor3232']),
    ('super.lyan', 'super.lyan', ARRAY['https://www.facebook.com/superlyan/']),
    ('superbuenonyc', 'superbuenonyc', ARRAY['https://www.facebook.com/superbuenonewyorkcity/']),
    ('supernovaballroom', 'supernovaballroom', NULL::text[]),
    ('svanen.oslo', 'svanen.oslo', ARRAY['https://www.facebook.com/svanen.oslo/']),
    ('sweetlibertymia', 'sweetlibertymia', ARRAY['https://www.facebook.com/mysweetliberty/', 'https://x.com/sweetlibertymia']),
    ('swiftsoho', 'swiftbars', ARRAY['https://www.facebook.com/barswift/', 'https://x.com/barswift']),
    ('tag.cocktails', 'tag.cocktails', ARRAY['https://www.facebook.com/tag.cocktails/']),
    ('tantannb', 'tantannb', NULL::text[]),
    ('tayer_elementary', 'tayer_elementary', NULL::text[]),
    ('tellcamellia', 'tellcamellia', ARRAY['https://www.facebook.com/tellcamellia/']),
    ('terminisoho', 'terminisoho', ARRAY['https://www.facebook.com/bar-termini-1425067291078635/']),
    ('terroirtapas', 'terroirtapas', NULL::text[]),
    ('tesouro.goa', 'tesouro.goa', NULL::text[]),
    ('the.bar.in.front.of.the.bar', 'the.bar.in.front.of.the.bar', ARRAY['https://www.youtube.com/@thebarinfrontofthebar6417']),
    ('the_bellwood', 'the_bellwood', NULL::text[]),
    ('the_clumsies', 'the_clumsies', NULL::text[]),
    ('the_sg_club', 'the_sg_club', ARRAY['https://www.facebook.com/thesgclub/']),
    ('thebaxterinnsydney', 'thebaxterinnsydney', ARRAY['https://www.facebook.com/The-Baxter-Inn-201601743255741/']),
    ('thebuenavistasf', 'thebuenavistasf', NULL::text[]),
    ('thecambridge_paris', 'thecambridge_paris', NULL::text[]),
    ('theclementebar', 'theclementebar', NULL::text[]),
    ('thecourtrome', 'thecourtrome', ARRAY['https://www.facebook.com/thecourtrome/']),
    ('thedeadrabbitny', 'thedeadrabbitny', ARRAY['https://www.tiktok.com/@thedeadrabbitpub', 'https://www.facebook.com/thedeadrabbitpub/', 'https://x.com/deadrabbitpub', 'https://www.youtube.com/@thedeadrabbitpub', 'https://www.threads.com/@thedeadrabbitny']),
    ('thedonovanbar', 'thedonovanbar', ARRAY['https://www.facebook.com/thedonovanbarlondon/']),
    ('thegoldentoothbar', 'thegoldentoothbar', NULL::text[]),
    ('thehanjiapairingdinner', 'thehanjiapairingdinner', NULL::text[]),
    ('thehouseofmachines_cpt', 'thehouseofmachines_cpt', NULL::text[]),
    ('thekeeferbar', 'thekeeferbar', ARRAY['https://www.facebook.com/thekeeferbar/', 'https://x.com/thekeeferbar']),
    ('thelobo_syd', 'thelobo_syd', ARRAY['https://www.facebook.com/thelobosydney/']),
    ('theoldman_hk', 'theoldman_hk', ARRAY['https://www.facebook.com/theoldmanhk/']),
    ('theoppositeshk', 'theoppositeshk', ARRAY['https://www.facebook.com/theoppositeshk/']),
    ('theoriolebar', 'theoriolebar', ARRAY['https://www.facebook.com/oriolebar/']),
    ('thepontiachk', 'wearethepontiac', NULL::text[]),
    ('thesavoryproject', 'thesavoryproject_', NULL::text[]),
    ('thesilverdollar', 'thesilverdollar', ARRAY['https://www.facebook.com/thesilverdollarlouisville/']),
    ('thewiseking_hk', 'thewiseking_hk', ARRAY['https://www.facebook.com/thewisekinghk/']),
    ('threesheetssoho', 'threesheetsbars', NULL::text[]),
    ('threexco_kl', 'threexco_kl', ARRAY['https://www.facebook.com/threexco/']),
    ('thunderboltla', 'thunderboltla', ARRAY['https://www.facebook.com/thunderboltlosangeles/']),
    ('tikiti1961', 'tikiti1961', ARRAY['https://www.facebook.com/tiki-ti-39568358564/', 'https://x.com/tiki_ti']),
    ('tjoget', 'tjoget', ARRAY['https://www.facebook.com/tjogethornstull/']),
    ('tlecan', 'tlecan', NULL::text[]),
    ('tommysmexican', 'tommysmexican', NULL::text[]),
    ('trailerh', 'trailerh', ARRAY['https://www.facebook.com/trailerhappiness/']),
    ('trickdogbar', 'trickdogbar', NULL::text[]),
    ('tropiccitybkk', 'tropiccitybkk', ARRAY['https://www.facebook.com/tropiccitybkk/']),
    ('truelaurelsf', 'truelaurelsf', ARRAY['https://x.com/truelaurelsf']),
    ('uglybutterflybyah', 'uglybutterflybyah', NULL::text[]),
    ('uniontradingco', 'uniontradingco', NULL::text[]),
    ('velvet.berlin', 'velvet.berlin', ARRAY['https://www.facebook.com/velvetberlin/']),
    ('venderbar', 'venderbar', NULL::text[]),
    ('vesperbkk', 'vesperbkk', ARRAY['https://www.facebook.com/vesperbkk/']),
    ('viajantebar', 'viajantebar', ARRAY['https://www.tiktok.com/@viajante87bar']),
    ('viceversamiami', 'viceversamiami', NULL::text[]),
    ('victoraudiobar', 'victoraudiobar', NULL::text[]),
    ('violethourchicago', 'violethourchicago', ARRAY['https://www.facebook.com/theviolethour1/']),
    ('waltzbar', 'waltzbar', NULL::text[]),
    ('waxonberlin', 'waxonberlin', NULL::text[]),
    ('workshop14.hanoi', 'workshop14.hanoi', NULL::text[]),
    ('yachtclubbar', 'yachtclubbar', NULL::text[]),
    ('zapotebar', 'zapotebar', NULL::text[]),
    ('zest.seoul', 'zest.seoul', NULL::text[]),
    ('zumadubai', 'zumadubai', NULL::text[])
) AS v ("handle", "instagram", "social_links")
WHERE p.handle = v.handle
  AND p.kind = 'bar';
