-- Specs for the 74 catalog classics, and their notes in our own words.
--
-- 20261002033302_content_rights dropped the specs these drinks had copied
-- from Punch and Difford's Guide, but kept a "Spec adapted from Punch (url)"
-- line in the notes. So the classics (Negroni, Martini, Daiquiri...) showed a
-- citation and no recipe. This gives each one a house spec and drops the
-- citation, along with the sentences that quoted those sites.
--
-- Proportions are facts: a Negroni is equal parts whoever prints it. The
-- specs below are the common modern builds, with our own method and garnish,
-- and every ingredient is one already on the shared list.
--
-- Only touches a drink that still has no spec, and only rewrites notes that
-- still carry the citation, so an edit made since is kept and a re-run
-- changes nothing.

-- Seeded drinks don't queue automatic sketches.
SET "app.image_worker" = 'on';

CREATE TEMP TABLE "fix_drinks" ("name" text, "glass" text, "ice" text, "method" text, "notes" text);
CREATE TEMP TABLE "fix_lines" ("drink" text, "pos" int, "amount" numeric, "unit" text,
    "ingredient" text, "prep" text, "optional" boolean);

INSERT INTO "fix_drinks" VALUES
    ($q$Alaska$q$, $q$Nick & Nora$q$, NULL, $q$Stir$q$, $q$The earliest known recipe appears in Jacques Straub's 1914 book Drinks, making the Alaska one of the oldest cocktails built on yellow Chartreuse, and the 1930 Savoy Cocktail Book later praised it. It was first made with rounder Old Tom gin. London dry stood in once Old Tom disappeared, and the style's return around 2007 let bartenders make the older, mellower version again.$q$),
    ($q$Americano$q$, $q$Highball$q$, $q$Cubes$q$, $q$Build$q$, NULL),
    ($q$Aperol Spritz$q$, $q$Wine$q$, $q$Cubes$q$, $q$Build$q$, $q$The spritz grew out of a 19th-century habit in the Veneto of splashing water into wine, which later picked up bitters and soda. Aperol, the bittersweet aperitivo from Padua, turned that regional ritual into a fixed three-two-one formula of prosecco, Aperol and soda. By the mid-2010s it had spread across Europe and the US, usually served in a big wine glass over plenty of ice.$q$),
    ($q$Aviation$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$Bamboo$q$, $q$Nick & Nora$q$, NULL, $q$Stir$q$, $q$German bartender Louis Eppinger created the Bamboo in the 1890s at the Grand Hotel in Yokohama, Japan, a hotel partly owned by American military men. The drink crossed the Pacific quickly, turning up on American menus by 1901 and later being sold bottled across the country. It is an equal-parts mix of dry sherry and dry vermouth with two kinds of bitters; some bartenders add a little rich syrup to round it out.$q$),
    ($q$Bee's Knees$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$The Bee's Knees is generally dated to American Prohibition, when honey and lemon helped cover up rough bootleg gin. It is a simple twist on the Gin Sour, and its name is 1920s slang for something excellent, alongside phrases like 'the cat's whiskers.' It came back with the revival's interest in vintage drinking.$q$),
    ($q$Bellini$q$, $q$Flute$q$, NULL, $q$Build$q$, $q$Giuseppe Cipriani created the Bellini at Harry's Bar in Venice in the 1940s and named it after the painter Giovanni Bellini for its rosy colour. Harry's still makes it only with fresh, ripe white peaches, so it goes off the menu when they are out of season. There it comes in a short tumbler rather than a flute, and it is still the bar's most popular drink.$q$),
    ($q$Bijou$q$, $q$Coupe$q$, NULL, $q$Stir$q$, NULL),
    ($q$Bitter Mai Tai$q$, $q$Rocks$q$, $q$Crushed$q$, $q$Shake$q$, NULL),
    ($q$Bloody Mary$q$, $q$Highball$q$, $q$Cubes$q$, $q$Build$q$, $q$The Bloody Mary has almost as many origin stories as recipes. The most cited credits Fernand Petiot, who served an early version of vodka, tomato juice, lemon, salt, pepper and Worcestershire at Harry's New York Bar in Paris and later popularized it as the Red Snapper at the St. Regis's King Cole Bar in New York; rival claims name comedian George Jessel and a Chicago dive. It stayed fairly restrained until the late 1980s, then snowballed into the garnish-heavy brunch spectacle of the 2000s and 2010s.$q$),
    ($q$Bobby Burns$q$, $q$Coupe$q$, NULL, $q$Stir$q$, NULL),
    ($q$Boulevardier$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Stir$q$, $q$Think of it as half Negroni, half Manhattan. It is named for Erskine Gwynne, a 1920s Paris figure who ran a magazine for American expats, and it appears in Harry MacElhone's 1927 book Barflies and Cocktails. Because whiskey is heavier than gin, bartenders often adjust the bitter and sweet parts to suit the whiskey they choose.$q$),
    ($q$Bramble$q$, $q$Rocks$q$, $q$Crushed$q$, $q$Shake$q$, NULL),
    ($q$Brandy Crusta$q$, $q$Coupette$q$, NULL, $q$Shake$q$, $q$Italian bartender Joseph Santini created the Crusta in 1850s New Orleans, making it one of the city's first signature drinks and older than the Sazerac. Jerry Thomas published it in 1862, and though whiskey or gin could stand in, brandy became the definitive version. It faded in the early 20th century until Chris Hannah revived it in New Orleans in 2004; his version adds a little maraschino.$q$),
    ($q$Brooklyn$q$, $q$Coupe$q$, NULL, $q$Stir$q$, $q$The Brooklyn is an early 20th-century whiskey cocktail, the Manhattan's lesser-known neighbour. It faded after Prohibition largely because its ingredients, especially Amer Picon, became hard to find. Its revival owes much to bartenders making their own Picon substitutes, since the French amer is still scarce in the US; a bittersweet amaro is the usual stand-in.$q$),
    ($q$Caipirinha$q$, $q$Rocks$q$, $q$Crushed$q$, $q$Build$q$, NULL),
    ($q$Clover Club$q$, $q$Coupe$q$, NULL, $q$dry shake and shake$q$, $q$The Clover Club takes its name from an all-male club of Philadelphia lawyers and writers that met at the Bellevue-Stratford Hotel in the late 1800s, and the drink appeared later in the club's run. It slipped into obscurity, partly because of the egg white and partly because raspberry was written off as a feminine flavour. The cocktail revival brought it back, and Julie Reiner made it the signature of her Brooklyn bar named after it; her version adds dry vermouth.$q$),
    ($q$Corpse Reviver #2$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$The Corpse Reviver No. 2 comes from a pre-Prohibition family of hangover-cure 'reviver' drinks and first appeared in print in The Savoy Cocktail Book (1930), which jokes that four in quick succession will undo the revival. It is a lighter cousin of the Sidecar. Keep it truly equal parts: more lemon makes it sharp, more gin makes it dry. It takes no cherry.$q$),
    ($q$Cosmopolitan$q$, $q$Martini$q$, NULL, $q$Shake$q$, NULL),
    ($q$Daiquiri$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$Credit usually goes to Jennings Cox, an American mining engineer near the Cuban town of Daiquiri around the time of the Spanish-American War, though Cubans had long mixed rum, lime and sugar; Jeff Berry calls Cox the drink's midwife because his is the only story with a paper trail. Hemingway's 1930s Havana helped make it famous, and wartime whiskey shortages in the 1940s pushed Caribbean rum and the Daiquiri further into the mainstream. The real thing is a simple, balanced sour, nothing like the frozen chain-restaurant version.$q$),
    ($q$Division Bell$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$El Diablo$q$, $q$Highball$q$, $q$Cubes$q$, $q$Build$q$, $q$The El Diablo first appeared in print in Trader Vic's Book of Food and Drink in 1946. It shows Victor Bergeron applying his tiki habit of blending flavours to spirits beyond rum, in this case tequila. It became one of the lasting tequila classics of the 1940s and 1950s, with the blackcurrant liqueur giving it its purple tint.$q$),
    ($q$Espresso Martini$q$, $q$Martini$q$, NULL, $q$Shake$q$, $q$Dick Bradsell invented it in the 1980s (his daughter places it around 1985) as an off-menu Vodka Espresso at the Soho Brasserie in London, reportedly for a model who wanted a drink to wake her up and then knock her out; that first version was vodka, espresso and syrup on the rocks. It picked up coffee liqueur and a stemmed glass at Match EC1 in the late 1990s, taking the Espresso Martini name during the 'tini craze, and was briefly the Pharmaceutical Stimulant at Pharmacy in Notting Hill. Bradsell modelled its balance on the Brandy Alexander, and it has become one of the best-known coffee drinks since Irish Coffee.$q$),
    ($q$Fitzgerald$q$, $q$Rocks$q$, $q$Cubes$q$, $q$Shake$q$, $q$Dale DeGroff improvised the Fitzgerald in the early 1990s at the Rainbow Room's Promenade Bar in New York, when a regular tired of his summer Gin and Tonic asked for a new gin drink. It is essentially a Gin Sour lifted with aromatic bitters, and bartenders online later carried it onto craft menus worldwide.$q$),
    ($q$French 75$q$, $q$Flute$q$, NULL, $q$shake and top$q$, $q$The French 75 was made famous at the New York Bar in Paris (opened 1911, renamed Harry's New York Bar after Scottish bartender Harry MacElhone bought it in the 1920s). It takes its name from a French 75mm artillery gun of World War I, a nod to its kick. Some records point to Cognac as the original base, fitting its French roots, though a gin version appeared in print in 1927 and became the more common spec. Both are still made.$q$),
    ($q$Gimlet$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$The Gimlet dates to the mid-1800s and is essentially a gin sour made with lime, reportedly devised to get Royal Navy sailors to drink the lime ration that kept scurvy away. Its name may come from Thomas Desmond Gimlette, a naval surgeon of the era. It was traditionally made with Rose's lime cordial; many bartenders now use fresh lime and simple syrup, or a house lime cordial.$q$),
    ($q$Gold Rush$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Shake$q$, NULL),
    ($q$Hanky Panky$q$, $q$Coupe$q$, NULL, $q$Stir$q$, NULL),
    ($q$Hemingway Daiquiri$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$This Daiquiri riff was poured for Ernest Hemingway at El Floridita in Havana, the bar of Constante Ribalaigua, and is unusual for skipping simple syrup (often put down to Hemingway being diabetic). The 1930s original used only a teaspoon each of grapefruit and maraschino; by the 1940s it carried more grapefruit and just drops of maraschino, and his habit of ordering doubles gave rise to the name Papa Doble. Go easy on the maraschino: too much buries the rum in cherry and almond.$q$),
    ($q$Jack Rose$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$The Jack Rose is a New Jersey drink built on applejack, the 'Jersey Lightning' that is among America's oldest spirits, with Laird's still its best-known maker. Its name is disputed: one story credits the early 20th-century gangland figure Bald Jack Rose, another a Jersey City bartender named Frank J. May who went by Jack Rose. By the middle of the 20th century it was considered a drink every bartender should know.$q$),
    ($q$Jungle Bird$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Shake$q$, $q$Created around 1978 at the Aviary Bar of the Kuala Lumpur Hilton in Malaysia, the drink sat in obscurity until Jeff "Beachbum" Berry found it in the 1989 New American Bartender's Guide and reprinted it in his 2002 book Intoxica!, reading its vague "dark rum" as dark Jamaican. The original used a hefty 4 oz of pineapple juice; around 2010 Giuseppe González in New York cut the pineapple and switched to blackstrap rum to stand up to the Campari, and that bolder version is now the norm. The original bartender's name has not survived.$q$),
    ($q$Last Word$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$Lemon Drop$q$, $q$Martini$q$, NULL, $q$Shake$q$, $q$The Lemon Drop is traced to Norman Jay Hobday (known as Henry Africa) at his San Francisco fern bar, Henry Africa's, which ran from 1969 to 1986. Structurally it is a vodka Sidecar, and it helped lay the groundwork for the Cosmopolitan. The served-up Lemon Drop Martini became a hit of the 1990s Martini-glass era, alongside a shot version.$q$),
    ($q$Little Italy$q$, $q$Coupe$q$, NULL, $q$Stir$q$, $q$Audrey Saunders created the Little Italy at Pegu Club in New York in 2005, naming it for the neighbourhood a short walk from the bar. It adds Cynar to a rye Manhattan, blending Italian and American ingredients, and it became one of the bold Manhattan variations that pushed other bartenders to build their own riffs.$q$),
    ($q$Mai Tai$q$, $q$Rocks$q$, $q$Crushed$q$, $q$Shake$q$, $q$Victor 'Trader Vic' Bergeron created the Mai Tai at Trader Vic's in Oakland in 1944 for two friends visiting from Tahiti, and the name comes from the Tahitian word for good. Because the recipe was a trade secret, bars poured whatever they liked under the name, and after Bergeron took it to Hawaii in 1953 it was cut with pineapple juice and premixes, earning a reputation as the most abused drink around. Around 2010 bartenders such as Martin Cate and Jeff 'Beachbum' Berry led a return to the 1944 template of aged Jamaican rum, lime, curaçao and orgeat.$q$),
    ($q$Manhattan$q$, $q$Coupe$q$, NULL, $q$Stir$q$, $q$The Manhattan grew out of the Old Fashioned once sweet vermouth caught on in the late 19th century. Historians still argue over its birthplace, with the leading theories pointing to New York's Manhattan Club or a bartender named Black working in lower Manhattan in the 1870s. The popular tale tying it to Winston Churchill's mother is a myth: she was in England at the time.$q$),
    ($q$Margarita$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$Martinez$q$, $q$Coupe$q$, NULL, $q$Stir$q$, $q$Often called an ancestor of the Martini, it first appeared in print in O.H. Byron's 1884 The Modern Bartender's Guide. Its origin is disputed between a bar in Martinez, California, and Jerry Thomas mixing it for a traveller bound there. It was traditionally made with Old Tom gin; London dry gives a drier drink.$q$),
    ($q$Martini$q$, $q$Martini$q$, NULL, $q$Stir$q$, $q$Nobody can pin down exactly where the Martini began, but it most likely came after the Manhattan, growing out of sweet vermouth and sweeter gin until drier styles of both took over around 1900. Through the 20th century the bitters disappeared and the vermouth shrank to almost nothing, tilting the drink heavily toward gin. The cocktail revival brought vermouth and bitters back, though ratio, garnish and method are still hotly argued; five parts gin to one of vermouth is a common middle ground.$q$),
    ($q$Milano Torino$q$, $q$Rocks$q$, $q$Cubes$q$, $q$Build$q$, $q$First served around 1860 at Gaspare Campari's cafe in Milan, the drink is named for the hometowns of its two ingredients: Campari from Milan and vermouth from Turin. Often shortened to Mi-To, it is the bittersweet template that the Americano (add soda) and the Negroni (add gin) were built on.$q$),
    ($q$Mint Julep$q$, $q$Julep Cup$q$, $q$Crushed$q$, $q$Build$q$, $q$The Mint Julep dates to the 18th century, probably Virginia in the late 1700s, when silver cups and ice made it a drink of the wealthy. It spread across the South through the 1800s, and bourbon became the standard base after the Civil War, when brandy was scarce and the region was poor. Today it is tied to the Kentucky Derby, where well over 100,000 are poured over race weekend.$q$),
    ($q$Mojito$q$, $q$Highball$q$, $q$Cubes$q$, $q$Build$q$, NULL),
    ($q$Moscow Mule$q$, $q$Highball$q$, $q$Cubes$q$, $q$Build$q$, NULL),
    ($q$Naked and Famous$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$Joaquín Simó created it at Death & Co in New York around 2011 as a mezcal cross between the Last Word and the Paper Plane, calling it the illegitimate offspring of the two. Smoky mezcal balances herbal Chartreuse and bittersweet Aperol, and the riff has become a modern classic in its own right.$q$),
    ($q$Negroni$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Stir$q$, $q$The usual story puts its birth at Caffè Casoni in Florence in 1919, when bartender Fosco Scarselli made Count Negroni a stronger Americano by swapping the soda for gin (early accounts say only a few drops of gin). The equal-parts recipe did not show up in print until 1947, in Amedeo Gandiglio's Cocktails Portfolio. It was seen as a lowbrow drink in Italy from the late 1970s through the 1990s before brand campaigns, bartender competitions and the gin boom made it a pillar of the classic cocktail revival.$q$),
    ($q$New York Sour$q$, $q$Rocks$q$, $q$Cubes$q$, $q$Shake$q$, $q$Floating red wine on a Whiskey Sour was a late-19th-century flourish that predates Prohibition. The drink went by many names, including the Continental, Brunswick, Waldorf and Southern Whiskey Sour, before New York stuck. The dry red wine float is the whole point: skip it and you just have a Whiskey Sour.$q$),
    ($q$Oaxaca Old Fashioned$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Stir$q$, $q$Phil Ward created it at Death & Co in Manhattan in 2007, after owner David Kaplan brought in mezcal for the bar to play with (Kaplan also named the drink). It spread quickly across New York and took off when Ward opened the agave bar Mayahuel in 2009, where staff say they made a million of them. Putting smoky mezcal in a familiar Old Fashioned format made it far less intimidating, and it opened many American bartenders' eyes to tequila and mezcal in cocktails.$q$),
    ($q$Old Fashioned$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Stir$q$, $q$It is the original cocktail formula of spirit, sugar, bitters and water, the combination printed in 1806 as the first definition of a cocktail; the name came later in the 1800s as fancier new drinks arrived. During Prohibition bartenders started muddling in fruit and cherries to hide rough liquor, and that version stuck after repeal. The cocktail revival of the late 2000s brought the stripped-back original back from near extinction.$q$),
    ($q$Paloma$q$, $q$Highball$q$, $q$Cubes$q$, $q$Build$q$, $q$The Paloma (Spanish for dove) is a Mexican highball of unclear origin, often said to outsell the Margarita at home. The traditional build tops tequila and a squeeze of lime with grapefruit soda; many bars use fresh grapefruit juice, a little syrup and soda water instead.$q$),
    ($q$Paper Plane$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$Pegu Club$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$Penicillin$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Shake$q$, $q$Sam Ross, an Australian bartender who moved to New York in 2004, created it at Milk & Honey in 2005 while playing with a peated Compass Box whisky, partly inspired by the bar's bourbon-and-honey Gold Rush. It went on the menu around 2007 at a server's urging, and Ross's consulting work in Los Angeles that year helped spread it west. By the 2010s it was about as close to a household name as any cocktail since the Cosmopolitan, and it is often called the most riffed-on modern classic.$q$),
    ($q$Piña Colada$q$, $q$Highball$q$, $q$Crushed$q$, $q$Blitz$q$, $q$The Piña Colada grew out of an alcohol-free Cuban pineapple slush popular in the early 1900s. The Caribe Hilton in San Juan, Puerto Rico, claims to have invented the cocktail in 1954, but the New York Times described the drink in 1950 and credited it to Cuba. Two pop hits in 1978 and 1979 locked in its status as the definitive beach cocktail.$q$),
    ($q$Pisco Sour$q$, $q$Coupe$q$, NULL, $q$dry shake and shake$q$, NULL),
    ($q$Pompier$q$, $q$Highball$q$, $q$Cubes$q$, $q$Build$q$, $q$Pompier is French for firefighter, and the vermouth and cassis highball, also called the Vermouth Cassis, was a popular order in New York in the late 1930s. Keep the cassis light so the vermouth leads.$q$),
    ($q$Porn Star Martini$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$Douglas Ankrah created the drink at his Townhouse bar in London's Knightsbridge in the early 2000s; he first conceived it in Cape Town as the Maverick Martini, after a local gentlemen's club, and renamed it back in London. The sparkling wine comes as a separate chaser rather than a topper, sipped between mouthfuls as a palate cleanser. By 2019 it was reported as the most ordered cocktail in the UK, and Marks & Spencer renamed its canned version the Passion Star Martini.$q$),
    ($q$Ramos Gin Fizz$q$, $q$Fizz$q$, NULL, $q$dry shake and shake$q$, $q$Henry C. Ramos created the drink in 1888 at his Imperial Cabinet Saloon in New Orleans. He wanted it so light and cloudlike that he lined up a relay of bartenders to take turns shaking each one. A long dry shake, then a hard shake with ice, gives it the milkshake-like body; the soda goes in last to lift the tall foam cap.$q$),
    ($q$Red Hook$q$, $q$Coupe$q$, NULL, $q$Stir$q$, NULL),
    ($q$Remember the Maine$q$, $q$Coupe$q$, NULL, $q$Stir$q$, NULL),
    ($q$Rob Roy$q$, $q$Coupe$q$, NULL, $q$Stir$q$, $q$The Rob Roy was created at the Waldorf Astoria in Manhattan in 1897, essentially a Manhattan with Scotch in place of American whiskey. It takes its name from an operetta about the Scottish folk hero that had opened in Manhattan a few years earlier. It drinks leaner than the whiskey original, and blended Scotch works well.$q$),
    ($q$Sazerac$q$, $q$Small Rocks$q$, NULL, $q$Stir$q$, NULL),
    ($q$Sbagliato$q$, $q$Rocks$q$, $q$Cubes$q$, $q$Build$q$, $q$The Negroni Sbagliato is credited to Mirko Stocchetto, a Harry's Bar alumnus who bought Milan's Bar Basso in 1967; the story goes that he grabbed sparkling wine instead of gin while making a Negroni, sometime in the late 1960s or early 1970s. Sbagliato means mistaken in Italian, and Bar Basso, now run by his son Maurizio, still serves it in enormous hand-blown goblets.$q$),
    ($q$Sidecar$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$Its origins are split between London and Paris around the end of World War I, with Harry's New York Bar in Paris a leading contender; owner Harry MacElhone printed an equal-parts brandy, lemon and Cointreau recipe in his 1927 Barflies and Cocktails. It is essentially a Cognac sour sweetened with Cointreau, descended from the 19th-century New Orleans Brandy Crusta. Bartenders now find the old 1:1:1 ratio too tart with modern ingredients, and the sugared rim, borrowed from the Crusta, only enters written Sidecar recipes in the 1930s.$q$),
    ($q$Stinger$q$, $q$Coupe$q$, NULL, $q$Shake$q$, $q$The Stinger began around 1890 as the Bartholdi Cocktail, named for the Madison Square hotel where it was mixed: just Cognac and crème de menthe, shaken and served up. It became a 1920s high-society favourite (Reginald Vanderbilt reportedly made them daily), and Cary Grant's 1957 film Kiss Them For Me made it famous. It is still served up, or over crushed ice.$q$),
    ($q$Ti' Punch$q$, $q$Small Rocks$q$, NULL, $q$Build$q$, $q$The Ti' Punch (short for petit punch) is the everyday drink of Martinique, built from unaged rhum agricole distilled from fresh cane juice. It is traditionally self-served, which inspired the local saying that everyone prepares their own death. Strong rhum, a small coin of lime and a little cane syrup, with little or no ice: more lime or ice pushes it toward a Daiquiri.$q$),
    ($q$Tom Collins$q$, $q$Collins$q$, $q$Cubes$q$, $q$shake and top$q$, $q$The first printed recipe appears in the 1876 edition of Jerry Thomas's Bartender's Guide. Two origin stories compete: an American one tied to the Great Tom Collins Hoax of 1874, a prank that sent people hunting for a man who did not exist, and a British one crediting London bartender John Collins with a gin punch built on Old Tom gin. It is, in effect, the original hard lemonade.$q$),
    ($q$Tommy's Margarita$q$, $q$Rocks$q$, $q$Cubes$q$, $q$Shake$q$, $q$Julio Bermejo built this version at his family's Tommy's Mexican Restaurant in San Francisco in the early 1990s, dropping the orange liqueur and sweetening with agave syrup, then mostly a health-food product made from a plant related to tequila's source. He also swapped sour mix for fresh lime and discouraged the salt rim. The restaurant became a pilgrimage site for bartenders, and the recipe is now the default Margarita in a great many bars.$q$),
    ($q$Trinidad Sour$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$Tuxedo$q$, $q$Coupe$q$, NULL, $q$Stir$q$, NULL),
    ($q$Vesper$q$, $q$Martini$q$, NULL, $q$Stir$q$, $q$Ian Fleming invented the Vesper for James Bond in the 1953 novel Casino Royale, where Bond orders it shaken; many bartenders stir it. Historians debate whether Fleming meant vermouth rather than Kina Lillet. Because Lillet was reformulated in the mid-1980s into a lighter, sweeter aperitif, bartenders often swap in Cocchi Americano to get closer to the original.$q$),
    ($q$Vieux Carré$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Stir$q$, NULL),
    ($q$Whiskey Sour$q$, $q$Rocks$q$, $q$Cubes$q$, $q$dry shake and shake$q$, $q$The Whiskey Sour is the textbook sour (spirit, citrus, sugar) and the building block for a huge number of later cocktails. Adding egg white makes it the Boston Sour style. A related 19th-century offshoot, the New York Sour, floats red wine on top.$q$),
    ($q$White Lady$q$, $q$Coupe$q$, NULL, $q$Shake$q$, NULL),
    ($q$White Negroni$q$, $q$Rocks$q$, $q$Large Cube$q$, $q$Stir$q$, $q$London bartender Wayne Collins made the first White Negroni in 2001 near Bordeaux, while travelling to Vinexpo with Plymouth Gin's Nick Blacknell: they bought local French ingredients, using Lillet Blanc for vermouth and Suze for Campari, and garnished with pink grapefruit. It was largely forgotten in the UK until Plymouth ambassador Simon Ford brought it to New York, where Audrey Saunders served it at Bemelmans and Pegu Club, reportedly carrying Suze back from England. It took off once Suze was imported to the US in 2012, and most bars now make it in equal parts with a grapefruit twist.$q$)
;

INSERT INTO "fix_lines" VALUES
    ($q$Alaska$q$, 0, 2, $q$oz$q$, $q$Old Tom Gin$q$, NULL, false),
    ($q$Alaska$q$, 1, 0.5, $q$oz$q$, $q$Yellow Chartreuse$q$, NULL, false),
    ($q$Alaska$q$, 2, 2, $q$dash$q$, $q$Orange Bitters$q$, NULL, false),
    ($q$Alaska$q$, 3, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Americano$q$, 0, 1.5, $q$oz$q$, $q$Campari$q$, NULL, false),
    ($q$Americano$q$, 1, 1.5, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Americano$q$, 2, NULL, $q$top$q$, $q$Soda Water$q$, NULL, false),
    ($q$Americano$q$, 3, 1, $q$slice$q$, $q$Orange$q$, NULL, false),
    ($q$Aperol Spritz$q$, 0, 3, $q$oz$q$, $q$Prosecco$q$, NULL, false),
    ($q$Aperol Spritz$q$, 1, 2, $q$oz$q$, $q$Aperol$q$, NULL, false),
    ($q$Aperol Spritz$q$, 2, 1, $q$oz$q$, $q$Soda Water$q$, NULL, false),
    ($q$Aperol Spritz$q$, 3, 1, $q$slice$q$, $q$Orange$q$, NULL, false),
    ($q$Aviation$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Aviation$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Aviation$q$, 2, 0.5, $q$oz$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Aviation$q$, 3, 0.25, $q$oz$q$, $q$Crème de Violette$q$, NULL, false),
    ($q$Aviation$q$, 4, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Bamboo$q$, 0, 1.5, $q$oz$q$, $q$Fino Sherry$q$, NULL, false),
    ($q$Bamboo$q$, 1, 1.5, $q$oz$q$, $q$Dry Vermouth$q$, NULL, false),
    ($q$Bamboo$q$, 2, 2, $q$dash$q$, $q$Orange Bitters$q$, NULL, false),
    ($q$Bamboo$q$, 3, 1, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Bamboo$q$, 4, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Bee's Knees$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Bee's Knees$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Bee's Knees$q$, 2, 0.75, $q$oz$q$, $q$Honey Syrup$q$, NULL, false),
    ($q$Bee's Knees$q$, 3, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Bellini$q$, 0, 2, $q$oz$q$, $q$White Peach Purée$q$, NULL, false),
    ($q$Bellini$q$, 1, 4, $q$oz$q$, $q$Prosecco$q$, NULL, false),
    ($q$Bijou$q$, 0, 1, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Bijou$q$, 1, 1, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Bijou$q$, 2, 1, $q$oz$q$, $q$Green Chartreuse$q$, NULL, false),
    ($q$Bijou$q$, 3, 1, $q$dash$q$, $q$Orange Bitters$q$, NULL, false),
    ($q$Bijou$q$, 4, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Bitter Mai Tai$q$, 0, 1.5, $q$oz$q$, $q$Campari$q$, NULL, false),
    ($q$Bitter Mai Tai$q$, 1, 0.75, $q$oz$q$, $q$Jamaican Rum$q$, NULL, false),
    ($q$Bitter Mai Tai$q$, 2, 1, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Bitter Mai Tai$q$, 3, 0.75, $q$oz$q$, $q$Orgeat$q$, NULL, false),
    ($q$Bitter Mai Tai$q$, 4, 0.5, $q$oz$q$, $q$Curaçao$q$, NULL, false),
    ($q$Bitter Mai Tai$q$, 5, 1, $q$sprig$q$, $q$Mint$q$, NULL, false),
    ($q$Bloody Mary$q$, 0, 1.5, $q$oz$q$, $q$Vodka$q$, NULL, false),
    ($q$Bloody Mary$q$, 1, 3, $q$oz$q$, $q$Tomato Juice$q$, NULL, false),
    ($q$Bloody Mary$q$, 2, 0.5, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Bloody Mary$q$, 3, 2, $q$dash$q$, $q$Worcestershire Sauce$q$, NULL, false),
    ($q$Bloody Mary$q$, 4, 2, $q$dash$q$, $q$Hot Sauce$q$, NULL, false),
    ($q$Bloody Mary$q$, 5, 1, $q$pinch$q$, $q$Celery Salt$q$, NULL, false),
    ($q$Bloody Mary$q$, 6, 1, $q$pinch$q$, $q$Black Pepper$q$, NULL, false),
    ($q$Bloody Mary$q$, 7, 1, $q$each$q$, $q$Celery$q$, $q$a stick$q$, false),
    ($q$Bloody Mary$q$, 8, 1, $q$wedge$q$, $q$Lemon$q$, NULL, false),
    ($q$Bobby Burns$q$, 0, 1.5, $q$oz$q$, $q$Blended Scotch$q$, NULL, false),
    ($q$Bobby Burns$q$, 1, 1.5, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Bobby Burns$q$, 2, 1, $q$bsp$q$, $q$Bénédictine$q$, NULL, false),
    ($q$Bobby Burns$q$, 3, 1, $q$peel$q$, $q$Lemon$q$, NULL, false),
    ($q$Boulevardier$q$, 0, 1.5, $q$oz$q$, $q$Bourbon$q$, NULL, false),
    ($q$Boulevardier$q$, 1, 1, $q$oz$q$, $q$Campari$q$, NULL, false),
    ($q$Boulevardier$q$, 2, 1, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Boulevardier$q$, 3, 1, $q$peel$q$, $q$Orange$q$, NULL, false),
    ($q$Bramble$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Bramble$q$, 1, 1, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Bramble$q$, 2, 0.5, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Bramble$q$, 3, 0.5, $q$oz$q$, $q$Crème de Mûre$q$, $q$drizzled over the top$q$, false),
    ($q$Bramble$q$, 4, 2, $q$each$q$, $q$Blackberry$q$, NULL, false),
    ($q$Bramble$q$, 5, 1, $q$slice$q$, $q$Lemon$q$, NULL, false),
    ($q$Brandy Crusta$q$, 0, 2, $q$oz$q$, $q$Cognac$q$, NULL, false),
    ($q$Brandy Crusta$q$, 1, 0.5, $q$oz$q$, $q$Curaçao$q$, NULL, false),
    ($q$Brandy Crusta$q$, 2, 0.5, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Brandy Crusta$q$, 3, 1, $q$bsp$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Brandy Crusta$q$, 4, 1, $q$bsp$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Brandy Crusta$q$, 5, 1, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Brandy Crusta$q$, 6, 1, $q$rim$q$, $q$Sugar$q$, NULL, false),
    ($q$Brandy Crusta$q$, 7, 1, $q$peel$q$, $q$Lemon$q$, $q$one long spiral, lining the glass$q$, false),
    ($q$Brooklyn$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Brooklyn$q$, 1, 1, $q$oz$q$, $q$Dry Vermouth$q$, NULL, false),
    ($q$Brooklyn$q$, 2, 0.25, $q$oz$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Brooklyn$q$, 3, 0.25, $q$oz$q$, $q$Amer Picon$q$, $q$or a bittersweet amaro$q$, false),
    ($q$Brooklyn$q$, 4, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Caipirinha$q$, 0, 2, $q$oz$q$, $q$Cachaça$q$, NULL, false),
    ($q$Caipirinha$q$, 1, NULL, NULL, $q$Lime$q$, $q$half a lime, cut into wedges and muddled$q$, false),
    ($q$Caipirinha$q$, 2, 2, $q$tsp$q$, $q$Sugar$q$, NULL, false),
    ($q$Clover Club$q$, 0, 1.5, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Clover Club$q$, 1, 0.5, $q$oz$q$, $q$Dry Vermouth$q$, NULL, false),
    ($q$Clover Club$q$, 2, 0.5, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Clover Club$q$, 3, 0.5, $q$oz$q$, $q$Raspberry Syrup$q$, NULL, false),
    ($q$Clover Club$q$, 4, 0.5, $q$oz$q$, $q$Egg White$q$, NULL, false),
    ($q$Clover Club$q$, 5, 2, $q$each$q$, $q$Raspberry$q$, NULL, false),
    ($q$Corpse Reviver #2$q$, 0, 0.75, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Corpse Reviver #2$q$, 1, 0.75, $q$oz$q$, $q$Lillet$q$, NULL, false),
    ($q$Corpse Reviver #2$q$, 2, 0.75, $q$oz$q$, $q$Cointreau$q$, NULL, false),
    ($q$Corpse Reviver #2$q$, 3, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Corpse Reviver #2$q$, 4, 1, $q$dash$q$, $q$Absinthe$q$, $q$rinse the glass$q$, false),
    ($q$Cosmopolitan$q$, 0, 1.5, $q$oz$q$, $q$Citron Vodka$q$, NULL, false),
    ($q$Cosmopolitan$q$, 1, 0.5, $q$oz$q$, $q$Cointreau$q$, NULL, false),
    ($q$Cosmopolitan$q$, 2, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Cosmopolitan$q$, 3, 1, $q$oz$q$, $q$Cranberry Juice$q$, NULL, false),
    ($q$Cosmopolitan$q$, 4, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Daiquiri$q$, 0, 2, $q$oz$q$, $q$White Rum$q$, NULL, false),
    ($q$Daiquiri$q$, 1, 1, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Daiquiri$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Daiquiri$q$, 3, 1, $q$wheel$q$, $q$Lime$q$, NULL, false),
    ($q$Division Bell$q$, 0, 1, $q$oz$q$, $q$Mezcal$q$, NULL, false),
    ($q$Division Bell$q$, 1, 0.75, $q$oz$q$, $q$Aperol$q$, NULL, false),
    ($q$Division Bell$q$, 2, 0.5, $q$oz$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Division Bell$q$, 3, 0.75, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Division Bell$q$, 4, 1, $q$twist$q$, $q$Grapefruit$q$, NULL, false),
    ($q$El Diablo$q$, 0, 1.5, $q$oz$q$, $q$Reposado Tequila$q$, NULL, false),
    ($q$El Diablo$q$, 1, 0.5, $q$oz$q$, $q$Crème de Cassis$q$, NULL, false),
    ($q$El Diablo$q$, 2, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$El Diablo$q$, 3, NULL, $q$top$q$, $q$Ginger Beer$q$, NULL, false),
    ($q$El Diablo$q$, 4, 1, $q$wedge$q$, $q$Lime$q$, NULL, false),
    ($q$Espresso Martini$q$, 0, 1.5, $q$oz$q$, $q$Vodka$q$, NULL, false),
    ($q$Espresso Martini$q$, 1, 1, $q$oz$q$, $q$Espresso$q$, $q$freshly pulled$q$, false),
    ($q$Espresso Martini$q$, 2, 0.5, $q$oz$q$, $q$Coffee Liqueur$q$, NULL, false),
    ($q$Espresso Martini$q$, 3, 0.25, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Espresso Martini$q$, 4, 3, $q$each$q$, $q$Coffee Beans$q$, NULL, false),
    ($q$Fitzgerald$q$, 0, 1.5, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Fitzgerald$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Fitzgerald$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Fitzgerald$q$, 3, 2, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Fitzgerald$q$, 4, 1, $q$wheel$q$, $q$Lemon$q$, NULL, false),
    ($q$French 75$q$, 0, 1, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$French 75$q$, 1, 0.5, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$French 75$q$, 2, 0.5, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$French 75$q$, 3, 3, $q$oz$q$, $q$Champagne$q$, NULL, false),
    ($q$French 75$q$, 4, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Gimlet$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Gimlet$q$, 1, 0.75, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Gimlet$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Gimlet$q$, 3, 1, $q$wheel$q$, $q$Lime$q$, NULL, false),
    ($q$Gold Rush$q$, 0, 2, $q$oz$q$, $q$Bourbon$q$, NULL, false),
    ($q$Gold Rush$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Gold Rush$q$, 2, 0.75, $q$oz$q$, $q$Honey Syrup$q$, NULL, false),
    ($q$Hanky Panky$q$, 0, 1.5, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Hanky Panky$q$, 1, 1.5, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Hanky Panky$q$, 2, 2, $q$dash$q$, $q$Fernet-Branca$q$, NULL, false),
    ($q$Hanky Panky$q$, 3, 1, $q$peel$q$, $q$Orange$q$, NULL, false),
    ($q$Hemingway Daiquiri$q$, 0, 2, $q$oz$q$, $q$White Rum$q$, NULL, false),
    ($q$Hemingway Daiquiri$q$, 1, 0.75, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Hemingway Daiquiri$q$, 2, 0.5, $q$oz$q$, $q$Grapefruit Juice$q$, NULL, false),
    ($q$Hemingway Daiquiri$q$, 3, 0.25, $q$oz$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Hemingway Daiquiri$q$, 4, 1, $q$wheel$q$, $q$Lime$q$, NULL, false),
    ($q$Jack Rose$q$, 0, 2, $q$oz$q$, $q$Applejack$q$, NULL, false),
    ($q$Jack Rose$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Jack Rose$q$, 2, 0.5, $q$oz$q$, $q$Grenadine$q$, NULL, false),
    ($q$Jack Rose$q$, 3, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Jungle Bird$q$, 0, 1.5, $q$oz$q$, $q$Dark Rum$q$, $q$blackstrap$q$, false),
    ($q$Jungle Bird$q$, 1, 0.75, $q$oz$q$, $q$Campari$q$, NULL, false),
    ($q$Jungle Bird$q$, 2, 1.5, $q$oz$q$, $q$Pineapple Juice$q$, NULL, false),
    ($q$Jungle Bird$q$, 3, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Jungle Bird$q$, 4, 0.5, $q$oz$q$, $q$Demerara Syrup$q$, NULL, false),
    ($q$Jungle Bird$q$, 5, 1, $q$wedge$q$, $q$Pineapple$q$, NULL, false),
    ($q$Last Word$q$, 0, 0.75, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Last Word$q$, 1, 0.75, $q$oz$q$, $q$Green Chartreuse$q$, NULL, false),
    ($q$Last Word$q$, 2, 0.75, $q$oz$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Last Word$q$, 3, 0.75, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Lemon Drop$q$, 0, 2, $q$oz$q$, $q$Citron Vodka$q$, NULL, false),
    ($q$Lemon Drop$q$, 1, 0.5, $q$oz$q$, $q$Cointreau$q$, NULL, false),
    ($q$Lemon Drop$q$, 2, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Lemon Drop$q$, 3, 0.5, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Lemon Drop$q$, 4, 1, $q$rim$q$, $q$Sugar$q$, NULL, false),
    ($q$Lemon Drop$q$, 5, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Little Italy$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Little Italy$q$, 1, 0.75, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Little Italy$q$, 2, 0.5, $q$oz$q$, $q$Cynar$q$, NULL, false),
    ($q$Little Italy$q$, 3, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Mai Tai$q$, 0, 2, $q$oz$q$, $q$Jamaican Rum$q$, $q$aged$q$, false),
    ($q$Mai Tai$q$, 1, 1, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Mai Tai$q$, 2, 0.5, $q$oz$q$, $q$Curaçao$q$, NULL, false),
    ($q$Mai Tai$q$, 3, 0.25, $q$oz$q$, $q$Orgeat$q$, NULL, false),
    ($q$Mai Tai$q$, 4, 0.25, $q$oz$q$, $q$Rich Simple Syrup$q$, NULL, false),
    ($q$Mai Tai$q$, 5, 1, $q$sprig$q$, $q$Mint$q$, NULL, false),
    ($q$Manhattan$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Manhattan$q$, 1, 1, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Manhattan$q$, 2, 2, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Manhattan$q$, 3, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Margarita$q$, 0, 2, $q$oz$q$, $q$Blanco Tequila$q$, NULL, false),
    ($q$Margarita$q$, 1, 0.75, $q$oz$q$, $q$Cointreau$q$, NULL, false),
    ($q$Margarita$q$, 2, 1, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Margarita$q$, 3, 1, $q$rim$q$, $q$Salt$q$, $q$half the rim$q$, true),
    ($q$Margarita$q$, 4, 1, $q$wedge$q$, $q$Lime$q$, NULL, false),
    ($q$Martinez$q$, 0, 1.5, $q$oz$q$, $q$Old Tom Gin$q$, NULL, false),
    ($q$Martinez$q$, 1, 1.5, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Martinez$q$, 2, 1, $q$bsp$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Martinez$q$, 3, 2, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Martinez$q$, 4, 1, $q$peel$q$, $q$Orange$q$, NULL, false),
    ($q$Martini$q$, 0, 2.5, $q$oz$q$, $q$London Dry Gin$q$, NULL, false),
    ($q$Martini$q$, 1, 0.5, $q$oz$q$, $q$Dry Vermouth$q$, NULL, false),
    ($q$Martini$q$, 2, 1, $q$dash$q$, $q$Orange Bitters$q$, NULL, false),
    ($q$Martini$q$, 3, 1, $q$twist$q$, $q$Lemon$q$, $q$or an olive$q$, false),
    ($q$Milano Torino$q$, 0, 1.5, $q$oz$q$, $q$Campari$q$, NULL, false),
    ($q$Milano Torino$q$, 1, 1.5, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Milano Torino$q$, 2, 1, $q$slice$q$, $q$Orange$q$, NULL, false),
    ($q$Mint Julep$q$, 0, 2.5, $q$oz$q$, $q$Bourbon$q$, NULL, false),
    ($q$Mint Julep$q$, 1, 0.5, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Mint Julep$q$, 2, NULL, NULL, $q$Mint$q$, $q$8 to 10 leaves, gently pressed$q$, false),
    ($q$Mint Julep$q$, 3, 1, $q$sprig$q$, $q$Mint$q$, NULL, false),
    ($q$Mojito$q$, 0, 2, $q$oz$q$, $q$White Rum$q$, NULL, false),
    ($q$Mojito$q$, 1, 1, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Mojito$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Mojito$q$, 3, NULL, NULL, $q$Mint$q$, $q$6 to 8 leaves, gently pressed$q$, false),
    ($q$Mojito$q$, 4, NULL, $q$top$q$, $q$Soda Water$q$, NULL, false),
    ($q$Mojito$q$, 5, 1, $q$sprig$q$, $q$Mint$q$, NULL, false),
    ($q$Moscow Mule$q$, 0, 2, $q$oz$q$, $q$Vodka$q$, NULL, false),
    ($q$Moscow Mule$q$, 1, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Moscow Mule$q$, 2, 4, $q$oz$q$, $q$Ginger Beer$q$, NULL, false),
    ($q$Moscow Mule$q$, 3, 1, $q$wedge$q$, $q$Lime$q$, NULL, false),
    ($q$Naked and Famous$q$, 0, 0.75, $q$oz$q$, $q$Mezcal$q$, NULL, false),
    ($q$Naked and Famous$q$, 1, 0.75, $q$oz$q$, $q$Yellow Chartreuse$q$, NULL, false),
    ($q$Naked and Famous$q$, 2, 0.75, $q$oz$q$, $q$Aperol$q$, NULL, false),
    ($q$Naked and Famous$q$, 3, 0.75, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Negroni$q$, 0, 1, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Negroni$q$, 1, 1, $q$oz$q$, $q$Campari$q$, NULL, false),
    ($q$Negroni$q$, 2, 1, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Negroni$q$, 3, 1, $q$peel$q$, $q$Orange$q$, NULL, false),
    ($q$New York Sour$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, $q$or bourbon$q$, false),
    ($q$New York Sour$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$New York Sour$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$New York Sour$q$, 3, 0.5, $q$oz$q$, $q$Red Wine$q$, $q$dry, floated on top$q$, false),
    ($q$Oaxaca Old Fashioned$q$, 0, 1.5, $q$oz$q$, $q$Reposado Tequila$q$, NULL, false),
    ($q$Oaxaca Old Fashioned$q$, 1, 0.5, $q$oz$q$, $q$Mezcal$q$, NULL, false),
    ($q$Oaxaca Old Fashioned$q$, 2, 1, $q$bsp$q$, $q$Agave Syrup$q$, NULL, false),
    ($q$Oaxaca Old Fashioned$q$, 3, 2, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Oaxaca Old Fashioned$q$, 4, 1, $q$peel$q$, $q$Orange$q$, $q$flamed$q$, false),
    ($q$Old Fashioned$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, $q$or bourbon$q$, false),
    ($q$Old Fashioned$q$, 1, 0.25, $q$oz$q$, $q$Simple Syrup$q$, $q$or a sugar cube$q$, false),
    ($q$Old Fashioned$q$, 2, 2, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Old Fashioned$q$, 3, 1, $q$peel$q$, $q$Orange$q$, NULL, false),
    ($q$Paloma$q$, 0, 2, $q$oz$q$, $q$Blanco Tequila$q$, NULL, false),
    ($q$Paloma$q$, 1, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Paloma$q$, 2, 1, $q$pinch$q$, $q$Salt$q$, NULL, false),
    ($q$Paloma$q$, 3, NULL, $q$top$q$, $q$Grapefruit Soda$q$, NULL, false),
    ($q$Paloma$q$, 4, 1, $q$wedge$q$, $q$Lime$q$, NULL, false),
    ($q$Paper Plane$q$, 0, 0.75, $q$oz$q$, $q$Bourbon$q$, NULL, false),
    ($q$Paper Plane$q$, 1, 0.75, $q$oz$q$, $q$Aperol$q$, NULL, false),
    ($q$Paper Plane$q$, 2, 0.75, $q$oz$q$, $q$Nonino$q$, NULL, false),
    ($q$Paper Plane$q$, 3, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Pegu Club$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Pegu Club$q$, 1, 0.75, $q$oz$q$, $q$Curaçao$q$, NULL, false),
    ($q$Pegu Club$q$, 2, 0.75, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Pegu Club$q$, 3, 1, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Pegu Club$q$, 4, 1, $q$dash$q$, $q$Orange Bitters$q$, NULL, false),
    ($q$Pegu Club$q$, 5, 1, $q$twist$q$, $q$Lime$q$, NULL, false),
    ($q$Penicillin$q$, 0, 2, $q$oz$q$, $q$Blended Scotch$q$, NULL, false),
    ($q$Penicillin$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Penicillin$q$, 2, 0.75, $q$oz$q$, $q$Honey-ginger Syrup$q$, NULL, false),
    ($q$Penicillin$q$, 3, 0.25, $q$oz$q$, $q$Islay Scotch$q$, $q$floated on top$q$, false),
    ($q$Penicillin$q$, 4, 1, $q$each$q$, $q$Candied Ginger$q$, NULL, false),
    ($q$Piña Colada$q$, 0, 2, $q$oz$q$, $q$White Rum$q$, NULL, false),
    ($q$Piña Colada$q$, 1, 1.5, $q$oz$q$, $q$Cream of Coconut$q$, NULL, false),
    ($q$Piña Colada$q$, 2, 3, $q$oz$q$, $q$Pineapple Juice$q$, NULL, false),
    ($q$Piña Colada$q$, 3, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Piña Colada$q$, 4, 1, $q$wedge$q$, $q$Pineapple$q$, NULL, false),
    ($q$Pisco Sour$q$, 0, 2, $q$oz$q$, $q$Pisco$q$, NULL, false),
    ($q$Pisco Sour$q$, 1, 1, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Pisco Sour$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Pisco Sour$q$, 3, 0.75, $q$oz$q$, $q$Egg White$q$, NULL, false),
    ($q$Pisco Sour$q$, 4, 3, $q$dash$q$, $q$Angostura$q$, $q$dotted on the foam$q$, false),
    ($q$Pompier$q$, 0, 2, $q$oz$q$, $q$Dry Vermouth$q$, NULL, false),
    ($q$Pompier$q$, 1, 0.5, $q$oz$q$, $q$Crème de Cassis$q$, NULL, false),
    ($q$Pompier$q$, 2, NULL, $q$top$q$, $q$Soda Water$q$, NULL, false),
    ($q$Pompier$q$, 3, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Porn Star Martini$q$, 0, 1.5, $q$oz$q$, $q$Vanilla Vodka$q$, NULL, false),
    ($q$Porn Star Martini$q$, 1, 0.5, $q$oz$q$, $q$Passion Fruit Liqueur$q$, NULL, false),
    ($q$Porn Star Martini$q$, 2, 1, $q$oz$q$, $q$Passion Fruit Purée$q$, NULL, false),
    ($q$Porn Star Martini$q$, 3, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Porn Star Martini$q$, 4, 0.25, $q$oz$q$, $q$Vanilla Syrup$q$, NULL, false),
    ($q$Porn Star Martini$q$, 5, 2, $q$oz$q$, $q$Sparkling Wine$q$, $q$in a shot glass on the side$q$, false),
    ($q$Porn Star Martini$q$, 6, 1, $q$each$q$, $q$Passion Fruit$q$, $q$half, floated$q$, false),
    ($q$Ramos Gin Fizz$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Ramos Gin Fizz$q$, 1, 0.5, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Ramos Gin Fizz$q$, 2, 0.5, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Ramos Gin Fizz$q$, 3, 1, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Ramos Gin Fizz$q$, 4, 1, $q$oz$q$, $q$Cream$q$, NULL, false),
    ($q$Ramos Gin Fizz$q$, 5, 0.75, $q$oz$q$, $q$Egg White$q$, NULL, false),
    ($q$Ramos Gin Fizz$q$, 6, 3, $q$dash$q$, $q$Orange Blossom Water$q$, NULL, false),
    ($q$Ramos Gin Fizz$q$, 7, 1, $q$oz$q$, $q$Soda Water$q$, $q$poured in last$q$, false),
    ($q$Red Hook$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Red Hook$q$, 1, 0.5, $q$oz$q$, $q$Punt E Mes$q$, NULL, false),
    ($q$Red Hook$q$, 2, 0.5, $q$oz$q$, $q$Maraschino Liqueur$q$, NULL, false),
    ($q$Red Hook$q$, 3, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Remember the Maine$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Remember the Maine$q$, 1, 0.75, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Remember the Maine$q$, 2, 2, $q$bsp$q$, $q$Cherry Heering$q$, NULL, false),
    ($q$Remember the Maine$q$, 3, 1, $q$dash$q$, $q$Absinthe$q$, $q$rinse the glass$q$, false),
    ($q$Remember the Maine$q$, 4, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Rob Roy$q$, 0, 2, $q$oz$q$, $q$Blended Scotch$q$, NULL, false),
    ($q$Rob Roy$q$, 1, 1, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Rob Roy$q$, 2, 2, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Rob Roy$q$, 3, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$Sazerac$q$, 0, 2, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Sazerac$q$, 1, 0.25, $q$oz$q$, $q$Simple Syrup$q$, $q$or a sugar cube$q$, false),
    ($q$Sazerac$q$, 2, 3, $q$dash$q$, $q$Peychaud's$q$, NULL, false),
    ($q$Sazerac$q$, 3, 1, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Sazerac$q$, 4, 1, $q$dash$q$, $q$Absinthe$q$, $q$rinse the glass$q$, false),
    ($q$Sazerac$q$, 5, 1, $q$peel$q$, $q$Lemon$q$, $q$expressed and discarded$q$, false),
    ($q$Sbagliato$q$, 0, 1, $q$oz$q$, $q$Campari$q$, NULL, false),
    ($q$Sbagliato$q$, 1, 1, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Sbagliato$q$, 2, 1.5, $q$oz$q$, $q$Prosecco$q$, NULL, false),
    ($q$Sbagliato$q$, 3, 1, $q$slice$q$, $q$Orange$q$, NULL, false),
    ($q$Sidecar$q$, 0, 2, $q$oz$q$, $q$Cognac$q$, NULL, false),
    ($q$Sidecar$q$, 1, 0.75, $q$oz$q$, $q$Cointreau$q$, NULL, false),
    ($q$Sidecar$q$, 2, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Sidecar$q$, 3, 1, $q$rim$q$, $q$Sugar$q$, NULL, true),
    ($q$Sidecar$q$, 4, 1, $q$twist$q$, $q$Orange$q$, NULL, false),
    ($q$Stinger$q$, 0, 2, $q$oz$q$, $q$Cognac$q$, NULL, false),
    ($q$Stinger$q$, 1, 0.75, $q$oz$q$, $q$Crème de Menthe$q$, $q$white$q$, false),
    ($q$Stinger$q$, 2, 1, $q$sprig$q$, $q$Mint$q$, NULL, false),
    ($q$Ti' Punch$q$, 0, 2, $q$oz$q$, $q$Rhum Agricole$q$, $q$blanc$q$, false),
    ($q$Ti' Punch$q$, 1, 1, $q$bsp$q$, $q$Cane Syrup$q$, NULL, false),
    ($q$Ti' Punch$q$, 2, 1, $q$slice$q$, $q$Lime$q$, $q$a small coin of peel and flesh, squeezed in$q$, false),
    ($q$Tom Collins$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Tom Collins$q$, 1, 1, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Tom Collins$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Tom Collins$q$, 3, NULL, $q$top$q$, $q$Soda Water$q$, NULL, false),
    ($q$Tom Collins$q$, 4, 1, $q$wheel$q$, $q$Lemon$q$, NULL, false),
    ($q$Tommy's Margarita$q$, 0, 2, $q$oz$q$, $q$Blanco Tequila$q$, NULL, false),
    ($q$Tommy's Margarita$q$, 1, 1, $q$oz$q$, $q$Lime Juice$q$, NULL, false),
    ($q$Tommy's Margarita$q$, 2, 0.5, $q$oz$q$, $q$Agave Syrup$q$, NULL, false),
    ($q$Tommy's Margarita$q$, 3, 1, $q$wedge$q$, $q$Lime$q$, NULL, false),
    ($q$Trinidad Sour$q$, 0, 1.5, $q$oz$q$, $q$Angostura$q$, NULL, false),
    ($q$Trinidad Sour$q$, 1, 1, $q$oz$q$, $q$Orgeat$q$, NULL, false),
    ($q$Trinidad Sour$q$, 2, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Trinidad Sour$q$, 3, 0.5, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Tuxedo$q$, 0, 2, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Tuxedo$q$, 1, 1, $q$oz$q$, $q$Fino Sherry$q$, NULL, false),
    ($q$Tuxedo$q$, 2, 2, $q$dash$q$, $q$Orange Bitters$q$, NULL, false),
    ($q$Tuxedo$q$, 3, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Vesper$q$, 0, 2.25, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$Vesper$q$, 1, 0.75, $q$oz$q$, $q$Vodka$q$, NULL, false),
    ($q$Vesper$q$, 2, 0.5, $q$oz$q$, $q$Lillet$q$, $q$or Cocchi Americano$q$, false),
    ($q$Vesper$q$, 3, 1, $q$peel$q$, $q$Lemon$q$, NULL, false),
    ($q$Vieux Carré$q$, 0, 0.75, $q$oz$q$, $q$Rye Whiskey$q$, NULL, false),
    ($q$Vieux Carré$q$, 1, 0.75, $q$oz$q$, $q$Cognac$q$, NULL, false),
    ($q$Vieux Carré$q$, 2, 0.75, $q$oz$q$, $q$Sweet Vermouth$q$, NULL, false),
    ($q$Vieux Carré$q$, 3, 1, $q$bsp$q$, $q$Bénédictine$q$, NULL, false),
    ($q$Vieux Carré$q$, 4, 2, $q$dash$q$, $q$Peychaud's$q$, NULL, false),
    ($q$Vieux Carré$q$, 5, 2, $q$dash$q$, $q$Angostura$q$, NULL, false),
    ($q$Vieux Carré$q$, 6, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$Whiskey Sour$q$, 0, 2, $q$oz$q$, $q$Bourbon$q$, NULL, false),
    ($q$Whiskey Sour$q$, 1, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$Whiskey Sour$q$, 2, 0.75, $q$oz$q$, $q$Simple Syrup$q$, NULL, false),
    ($q$Whiskey Sour$q$, 3, 0.5, $q$oz$q$, $q$Egg White$q$, NULL, true),
    ($q$Whiskey Sour$q$, 4, 1, $q$each$q$, $q$Maraschino Cherry$q$, NULL, false),
    ($q$White Lady$q$, 0, 1.5, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$White Lady$q$, 1, 0.75, $q$oz$q$, $q$Cointreau$q$, NULL, false),
    ($q$White Lady$q$, 2, 0.75, $q$oz$q$, $q$Lemon Juice$q$, NULL, false),
    ($q$White Lady$q$, 3, 0.5, $q$oz$q$, $q$Egg White$q$, NULL, true),
    ($q$White Lady$q$, 4, 1, $q$twist$q$, $q$Lemon$q$, NULL, false),
    ($q$White Negroni$q$, 0, 1, $q$oz$q$, $q$Gin$q$, NULL, false),
    ($q$White Negroni$q$, 1, 1, $q$oz$q$, $q$Lillet$q$, NULL, false),
    ($q$White Negroni$q$, 2, 1, $q$oz$q$, $q$Suze$q$, NULL, false),
    ($q$White Negroni$q$, 3, 1, $q$twist$q$, $q$Grapefruit$q$, NULL, false)
;

ALTER TABLE "fix_drinks" ADD COLUMN "item_id" uuid;
UPDATE "fix_drinks" f SET "item_id" = (
    SELECT i.id FROM "public"."items" i
    WHERE i.is_catalog AND i.item_type = 'cocktail' AND lower(i.name) = lower(f.name)
    ORDER BY i.created_at LIMIT 1
);

-- --- Notes: drop the citation (and, where given, the sentences quoting the site) ---

UPDATE "public"."items" i
SET "notes" = coalesce(f.notes, regexp_replace(i.notes, '\s*Spec (as )?adapted from [^\n]*$', ''))
FROM "fix_drinks" f
WHERE i.id = f.item_id
  AND i.notes ~ 'Spec (as )?adapted from';

-- --- Specs: only for drinks that have none ---

DELETE FROM "fix_drinks" f
WHERE f.item_id IS NULL
   OR EXISTS (SELECT 1 FROM "public"."recipes" r WHERE r.recipe_item_id = f.item_id);

-- Every name is on the shared list in production; a fresh database may lack
-- a brand or two, so add those (hidden from search, like the other seeds).
INSERT INTO "public"."items" ("name", "item_type", "hide_from_search")
SELECT DISTINCT ON (public.ingredient_key(l.ingredient)) l.ingredient, 'ingredient', true
FROM "fix_lines" l
JOIN "fix_drinks" f ON f.name = l.drink
WHERE public.resolve_ingredient(l.ingredient) IS NULL;

INSERT INTO "public"."recipes" ("recipe_item_id", "ingredient_item_id", "amount", "unit",
                                "preparation_notes", "is_optional", "sort_order")
SELECT f.item_id, public.resolve_ingredient(l.ingredient), l.amount, l.unit, l.prep, l.optional, l.pos
FROM "fix_lines" l
JOIN "fix_drinks" f ON f.name = l.drink;

UPDATE "public"."items" i SET
    "glassware_id" = coalesce(i.glassware_id, (SELECT g.id FROM "public"."items" g WHERE g.item_type = 'glassware' AND g.bar_id IS NULL AND lower(g.name) = lower(f.glass) ORDER BY g.created_at LIMIT 1)),
    "ice_id" = coalesce(i.ice_id, (SELECT c.id FROM "public"."items" c WHERE c.item_type = 'ice' AND c.bar_id IS NULL AND lower(c.name) = lower(f.ice) ORDER BY c.created_at LIMIT 1))
FROM "fix_drinks" f
WHERE i.id = f.item_id;

INSERT INTO "public"."item_methods" ("item_id", "method_item_id", "sort_order")
SELECT f.item_id, m.id, 0
FROM "fix_drinks" f
CROSS JOIN LATERAL (
    SELECT x.id FROM "public"."items" x
    WHERE x.item_type = 'method' AND x.bar_id IS NULL AND lower(x.name) = lower(f.method)
    ORDER BY x.created_at LIMIT 1
) m
WHERE NOT EXISTS (SELECT 1 FROM "public"."item_methods" im WHERE im.item_id = f.item_id);

DROP TABLE "fix_drinks", "fix_lines";

RESET "app.image_worker";
