-- The World's 50 Best Bars 2025 on Cocktail, and bars nobody has ranked yet
-- on the top bars list.
--
-- 1. Top bars listed only bars with a ranked drink (private.venue_scores), so
--    a bar someone added, or one of these, stayed off the list and the map
--    until somebody ranked a drink there. discover_top_bars() now also
--    returns public bars with no rankings as early rows (rankers 0), after
--    the bars people have started ranking, nearest first, then by name. Same
--    row shape; the app says "Not ranked yet" for them.
--
-- 2. The 50 bars from The World's 50 Best Bars 2025 (announced 8 Oct 2025),
--    as public, unclaimed venue profiles: name, street address, map point,
--    website and a short bio in our words, with the list position in the
--    bio. Each bar claims its profile as before (profile_claims), and
--    moderators edit, hide or remove them. A bar already on Cocktail with the
--    same name within 150 m (add_venue's duplicate rule) is left alone.
--    Caretaker's Cottage (No. 19) is a venue here: its profile is the venue's
--    own (bar_id set), not an unclaimed copy.
--    ponytail: logos aren't in this migration. They're files in the avatars
--    bucket, uploaded once per database and then set as avatar_url; the PR
--    says how. When the 2026 list is out (7 Oct 2026), a follow-up adds the
--    new bars and updates the positions in the bios.

-- --- Top bars, ranked or not ---

CREATE OR REPLACE FUNCTION "public"."discover_top_bars"(
    "p_latitude" double precision DEFAULT NULL,
    "p_longitude" double precision DEFAULT NULL,
    "p_radius_km" double precision DEFAULT 10,
    "p_country_code" "text" DEFAULT NULL,
    "p_city" "text" DEFAULT NULL,
    "p_limit" integer DEFAULT 20
) RETURNS TABLE("position" bigint, "venue_profile_id" "uuid", "handle" "text", "display_name" "text",
                "locality" "text", "city" "text", "latitude" double precision, "longitude" double precision,
                "distance_km" double precision, "score" numeric, "rankers" integer, "drinks" integer, "is_early" boolean)
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  WITH rows AS (
    SELECT a.id AS venue_profile_id, s.score, coalesce(s.rankers, 0) AS rankers, coalesce(s.drinks, 0) AS drinks,
           a.distance_km, coalesce(s.rankers, 0) >= private.ranking_min_rankers() AS ranked
    FROM private.bars_in_area(p_latitude, p_longitude, p_radius_km, p_country_code, p_city) a
    LEFT JOIN private.venue_scores s ON s.venue_profile_id = a.id
  ), numbered AS (
    SELECT r.*, row_number() OVER (
      PARTITION BY r.ranked
      ORDER BY CASE WHEN r.ranked THEN r.score END DESC NULLS LAST, r.rankers DESC, r.distance_km NULLS LAST,
               lower(p.display_name), r.venue_profile_id
    ) AS n
    FROM rows r
    JOIN public.profiles p ON p.id = r.venue_profile_id
  )
  SELECT CASE WHEN x.ranked THEN x.n END, p.id, p.handle, p.display_name, p.locality, p.city, p.latitude, p.longitude,
         x.distance_km, CASE WHEN x.ranked THEN x.score END, x.rankers, x.drinks, NOT x.ranked
  FROM numbered x
  JOIN public.profiles p ON p.id = x.venue_profile_id
  WHERE x.n <= least(greatest(coalesce(p_limit, 20), 1), 100)
  ORDER BY x.ranked DESC, x.n;
$$;

-- --- The World's 50 Best Bars 2025 ---

-- Rows are in list order. Websites are each bar's own (its Instagram when it
-- has no site). Addresses and points were checked against OpenStreetMap on
-- 29 Sep 2026; Lady Bee (moved to Barranco in 2025) and 1930 (moved in 2025)
-- are at their new addresses.
INSERT INTO "public"."profiles" ("kind", "handle", "display_name", "bio", "website", "is_public", "locality", "address_line",
                                 "postcode", "city", "region", "country_code", "latitude", "longitude",
                                 "bar_id", "claimed_at", "avatar_url")
SELECT 'bar', v.handle, v.name, v.bio, v.website, true, v.locality, v.address_line,
       v.postcode, v.city, v.region, v.country_code, v.latitude, v.longitude,
       b.id, CASE WHEN b.id IS NOT NULL THEN now() END, b.logo_url
FROM (VALUES
    ('barleonehk', 'Bar Leone', 'A casual neighbourhood bar modelled on the everyday bars of Rome, opened in 2023 by Roman bartender Lorenzo Antinori. It serves pared-back takes on classic cocktails made without lab equipment, plus mortadella sandwiches, and takes no reservations. No. 1 on The World''s 50 Best Bars 2025.', 'https://www.barleonehk.com/', 'Central', '11-15 Bridges Street', NULL, 'Hong Kong', NULL, 'HK', 22.28356, 114.15095, NULL),
    ('handshake_bar', 'Handshake Speakeasy', 'A two-level Art Deco speakeasy in Colonia Juárez behind an unmarked door. Drinks director Eric van Beek runs a kitchen-minded cocktail list across a moody ground-floor bar and a louder hip-hop basement, and the fig martini has been on since opening. No. 2 on The World''s 50 Best Bars 2025.', 'https://handshake.bar/', 'Juárez', 'Amberes 65', '06600', 'Mexico City', 'Ciudad de México', 'MX', 19.42432, -99.1648, NULL),
    ('sips.barcelona', 'Sips', 'An Eixample cocktail bar opened in 2021 by Simone Caporale and Marc Álvarez, built around a central island bar so guests watch every drink being made. It also houses Esencia, a 14-seat counter serving a tasting menu of small experimental sips. No. 3 on The World''s 50 Best Bars 2025.', 'https://sips.barcelona/', 'Eixample', 'Carrer de Muntaner, 108', '08036', 'Barcelona', 'Catalonia', 'ES', 41.38887, 2.15672, NULL),
    ('paradiso_barcelona', 'Paradiso', 'A cocktail bar in El Born entered through a fridge door at the back of a pastrami shop, founded by Giacomo Giannotti. Its theatrical drinks are developed in the in-house Paradiso Lab with a sustainability focus and served under a curved wooden ceiling. No. 4 on The World''s 50 Best Bars 2025.', 'https://paradiso.cat/', 'El Born', 'Carrer de Rera Palau, 4', '08003', 'Barcelona', 'Catalonia', 'ES', 41.38367, 2.1837, NULL),
    ('tayer_elementary', 'Tayēr + Elementary', 'A two-part bar from Monica Berg and Alex Kratena. Elementary, at the front, is a casual room for draught cocktails and the One Sip Martini; Tayēr, behind a partition, is a produce-led counter with a menu that changes daily. Closed for now after a fire in May 2026. No. 5 on The World''s 50 Best Bars 2025.', 'https://tayer-elementary.com/', 'Old Street', '152 Old Street', 'EC1V 9BW', 'London', NULL, 'GB', 51.52502, -0.09151, NULL),
    ('connaughtbar', 'Connaught Bar', 'The cocktail bar of The Connaught hotel in Mayfair, open since 2008 and led by director of mixology Agostino Perrone. It is known for its Martini trolley, where the bartender mixes each guest''s Martini at the table with a choice of house bitters. No. 6 on The World''s 50 Best Bars 2025.', 'https://www.maybourne.com/en/hotels/the-connaught/restaurants-bars/connaught-bar', 'Mayfair', 'The Connaught, Carlos Place', 'W1K 2AL', 'London', NULL, 'GB', 51.51018, -0.15022, NULL),
    ('moebiusmilano', 'Moebius Milano', 'A bar, bistro and music venue in a former textile warehouse near Milano Centrale, founded by Lorenzo Querci in 2019. The cocktail bar, led by Giovanni Allario, pours easygoing seasonal drinks next to a tapas bistro, a fine-dining room and a record store. No. 7 on The World''s 50 Best Bars 2025.', 'https://moebiusmilano.it/', 'Centrale', 'Via Alfredo Cappellini, 25', '20124', 'Milan', 'Lombardy', 'IT', 45.48143, 9.20287, NULL),
    ('line.athens', 'Line', 'A bar in a former art gallery in Petralona from Dimitris Dafopoulos with Vasilis Kyritsis and Nikos Bakoulis of The Clumsies. The team ferments its own fruit wines (Why-ins), beer and sourdough on site and reuses the leftovers in classics-inspired cocktails. No. 8 on The World''s 50 Best Bars 2025.', 'https://lineathens.gr/', 'Petralona', 'Agathodemonos 37', '118 53', 'Athens', 'Attica', 'GR', 37.96854, 23.70338, NULL),
    ('jiggerandponysg', 'Jigger & Pony', 'A cocktail bar founded in 2012 by Indra Kantono and Guoyi Gan, since 2018 in the lobby of the Amara hotel on Tanjong Pagar Road. It serves contemporary drinks rooted in the classics, with a new magazine-style menu released each year. No. 9 on The World''s 50 Best Bars 2025.', 'https://www.jiggerandpony.com/', 'Tanjong Pagar', '165 Tanjong Pagar Road, Amara Singapore', '088539', 'Singapore', NULL, 'SG', 1.27494, 103.84366, NULL),
    ('3monosbar', 'Tres Monos', 'A small, dark, graffiti-covered bar on a Palermo corner run by Sebastián Atienza, Charly Aguinsky and Gus Vocke. It works with Argentine producers on its own whiskey, sake, liqueurs and wines, and pours them in cocktails to a loud rock soundtrack. No. 10 on The World''s 50 Best Bars 2025.', 'https://www.instagram.com/3monosbar/', 'Palermo Soho', 'Guatemala 4899', 'C1425', 'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'AR', -34.58487, -58.4262, NULL),
    ('alquimicocartagena', 'Alquímico', 'Three-floor cocktail bar in a colonial mansion in Cartagena''s walled city, built around Colombian ingredients, many grown on the team''s own farm in Quindío. Each floor has its own menu, and the bar backs local farming, music and craft projects. No. 11 on The World''s 50 Best Bars 2025.', 'https://alquimico.com/', 'Centro Histórico', 'Calle del Colegio #34-24', '130001', 'Cartagena', 'Bolívar', 'CO', 10.42371, -75.54967, NULL),
    ('superbuenonyc', 'Superbueno', 'East Village cantina from Ignacio ''Nacho'' Jimenez that plays on Mexican-American flavours, with cocktails modelled on Mexican dishes and ingredients, frozen drinks on rotation and late-night street-food plates. No. 12 on The World''s 50 Best Bars 2025.', 'https://www.superbuenonyc.com/', 'East Village', '13 1st Avenue', '10003', 'New York', 'NY', 'US', 40.72345, -73.98855, NULL),
    ('ladybee.lima', 'Lady Bee', 'Lima cocktail bar and kitchen run by bartender Alonso Palomino, chef Gabriela León and Alejandra León, built on Peruvian produce with producers named on the menu. A native stingless bee inspires the name and many of the drinks. No. 13 on The World''s 50 Best Bars 2025.', 'https://ladybee.bar/', 'Barranco', 'Av. Pedro de Osma 205', '15063', 'Lima', 'Lima', 'PE', -12.15175, -77.02215, NULL),
    ('himkok.oslo', 'Himkok', 'Multi-level Oslo bar behind an unmarked door, with its own micro-distillery making aquavit, gin and vodka for Nordic-leaning cocktails, plus an upstairs draught-cocktail bar, a cider terrace out back and a barbershop. No. 14 on The World''s 50 Best Bars 2025.', 'https://www.himkok.no/', 'Sentrum', 'Storgata 27', '0184', 'Oslo', NULL, 'NO', 59.91427, 10.75152, NULL),
    ('bar.us.bkk', 'Bar Us', 'Small, dark ''drinking room'' on Sukhumvit Soi 26 run by Taln Rojanavanich and Aum Sawaengsupt, serving cocktails as a course-by-course menu (starter, main, after) from a lab-like back bar of jars, herbs and spices. No. 15 on The World''s 50 Best Bars 2025.', 'https://www.us-bar.com/', 'Sukhumvit', '61/37 Sukhumvit 26', '10110', 'Bangkok', NULL, 'TH', 13.72554, 100.56941, NULL),
    ('zest.seoul', 'Zest', 'Basement bar in Cheongdam co-founded by Dohyung ''Demie'' Kim, pairing minimalist cocktails with Korean produce and a zero-waste approach: peels, pulp and trimmings become house spirits, cordials and garnishes, and the bar keeps its own beehives. No. 16 on The World''s 50 Best Bars 2025.', 'https://www.instagram.com/zest.seoul/', 'Cheongdam-dong', 'B1, 26 Dosan-daero 55-gil', '06014', 'Seoul', NULL, 'KR', 37.52527, 127.04082, NULL),
    ('barnouveau', 'Bar Nouveau', 'Tiny two-level Marais bar themed on Art Nouveau, from Rémy Savage, twins Sara and Hadrien Moudoulaud and Marc Puzzuoli. A short list of six cocktails, walk-ins only, served in antique glassware. No. 17 on The World''s 50 Best Bars 2025.', 'https://barnouveau.fr/', 'Le Marais', '5 Rue des Haudriettes', '75003', 'Paris', 'Île-de-France', 'FR', 48.8615, 2.35756, NULL),
    ('benfiddich_tokyo', 'Bar Benfiddich', 'Fifteen-seat ninth-floor bar in Nishi-Shinjuku where owner Hiroyasu Kayama builds cocktails from herbs and botanicals grown on his family''s farm in Chichibu, alongside vintage spirits and house absinthe. No. 18 on The World''s 50 Best Bars 2025.', 'https://benfiddich.tokyo/', 'Nishi-Shinjuku', 'Yamatoya Building 9F, 1-13-7 Nishi-Shinjuku', '160-0023', 'Tokyo', 'Tokyo', 'JP', 35.68949, 139.6966, NULL),
    ('caretakers.cottage', 'Caretaker''s Cottage', 'Walk-in bar in a 1914 bluestone caretaker''s cottage behind Wesley Church in Melbourne''s city centre, run by Rob Libecans, Ryan Noreiks and Matt Stirling and known for martinis, milk punch and Guinness. No. 19 on The World''s 50 Best Bars 2025.', 'https://www.caretakerscottage.bar/', 'Melbourne CBD', '139-141 Little Lonsdale Street', '3000', 'Melbourne', 'VIC', 'AU', -37.80964, 144.96784, 'caretakers-cottage'),
    ('thecambridge_paris', 'The Cambridge Public House', 'Marais bar opened in 2019 by Hyacinthe Lescoët and Hugo Gallou that crosses a British pub with a cocktail bar, serving drinks, beers, natural wines and snacks with a strong sustainability focus; in 2024 it became the first bar certified as a B Corp. No. 20 on The World''s 50 Best Bars 2025.', 'https://www.thecambridge.paris/', 'Le Marais', '8 Rue de Poitou', '75003', 'Paris', 'Île-de-France', 'FR', 48.86145, 2.36417, NULL),
    ('satans_whiskers', 'Satan''s Whiskers', 'A neighbourhood cocktail bar in Bethnal Green, open since late 2013 and founded by Kevin Armstrong, Damian Benjamin and Fraser Chapman. Classics made fresh to order from a daily printed menu, taxidermy on the walls and a hip-hop soundtrack. No. 21 on The World''s 50 Best Bars 2025.', 'https://www.satanswhiskers.com/', 'Bethnal Green', '343 Cambridge Heath Road', 'E2 9RA', 'London', NULL, 'GB', 51.52949, -0.05616, NULL),
    ('localefirenze', 'Locale Firenze', 'Bar and restaurant inside the medieval Palazzo Concini, with a vaulted basement lab. The bar team, led by bar manager Fabio Fanni, reworks familiar classics with modern techniques and a low-waste approach, often drawing on the kitchen and seasonal produce. No. 22 on The World''s 50 Best Bars 2025.', 'https://www.localefirenze.it/', 'Santa Croce', 'Via delle Seggiole 12r', '50122', 'Florence', 'Tuscany', 'IT', 43.77119, 11.26001, NULL),
    ('tlecan', 'Tlecān', 'An intimate agave bar in Roma Norte whose name means ''place of fire'' in Náhuatl. Co-owner and head bartender Eli Martínez Bello sources mezcal, bacanora, sotol, raicilla and pox from small producers, served neat or in cocktails such as a clarified Paloma. No. 23 on The World''s 50 Best Bars 2025.', 'https://tlecan.com/', 'Roma Norte', 'Av. Álvaro Obregón 228, Local 2', '06700', 'Mexico City', 'Ciudad de México', 'MX', 19.41691, -99.16547, NULL),
    ('tantannb', 'Tan Tan', 'Half bar, half restaurant in Pinheiros, opened in 2015 by chef Thiago Bañares as a small Japanese noodle bar. Cocktails by bar chef Caio Carvalhaes sit alongside Asian dishes with Brazilian touches, and low and no-alcohol drinks share the same list. No. 24 on The World''s 50 Best Bars 2025.', 'https://www.tantan.com.br/tantan', 'Pinheiros', 'Rua Fradique Coutinho, 153', '05416-010', 'São Paulo', 'São Paulo', 'BR', -23.56514, -46.6852, NULL),
    ('mirrorbarcarlton', 'Mirror Bar', 'Lounge bar in the Radisson Blu Carlton Hotel built around three ideas: classy, art and nature. A full-size tree and bonsai fill the green room, and drinks come in glassware made with local artisans. Run by Stanislav Harciník and Peter Marcina. No. 25 on The World''s 50 Best Bars 2025.', 'https://www.mirrorbarcarlton.com/', 'Staré Mesto', 'Hviezdoslavovo námestie 3', '811 02', 'Bratislava', 'Bratislava Region', 'SK', 48.14139, 17.10901, NULL),
    ('cochinchina.bar', 'CoChinChina', 'Cocktail bar and restaurant in Palermo from bartender Inés de los Santos, themed on the old French colony in southern Vietnam. Drinks and Franco-Vietnamese plates like banh mi share a colourful room with a U-shaped bar, plus a quieter upstairs room, Arriba. No. 26 on The World''s 50 Best Bars 2025.', 'https://www.instagram.com/cochinchina.bar/', 'Palermo Soho', 'Armenia 1540', 'C1414', 'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'AR', -34.59034, -58.42886, NULL),
    ('baba_au_rum', 'Baba au Rum', 'A rum and cocktail bar in central Athens run by owner Thanos Prunarus, with more than 400 rums on the back bar. The menu leans on tiki and classic rum drinks as starting points for new cocktails, served in a modernist room with carefully chosen music. No. 27 on The World''s 50 Best Bars 2025.', 'https://www.babaaurum.com/', 'Historic Centre', 'Klitiou 6', '105 60', 'Athens', 'Attica', 'GR', 37.9774, 23.72978, NULL),
    ('nouvellevague_tirana', 'Nouvelle Vague', 'Family-run cocktail bar in Tirana''s Blloku, opened in 2012 by Sofokli and Evis Cali and named after French New Wave cinema. Its menu, led by head bartender Mariol Djata, builds on Albanian ingredients and raki from small producers. No. 28 on The World''s 50 Best Bars 2025.', 'https://nouvellevaguetirana.com/', 'Blloku', 'Rruga Pjetër Bogdani', NULL, 'Tirana', NULL, 'AL', 41.32114, 19.8148, NULL),
    ('hopeandsesame', 'Hope & Sesame', 'Opened in 2016 behind a small Cantonese shopfront in Dongshankou, run by Bastien Ciocca and Andrew Ho. Its cocktails draw on Cantonese flavours and ingredients, with a new themed menu each edition, and its Chinese name is 庙前冰室. No. 29 on The World''s 50 Best Bars 2025.', 'https://hopeandsesame.cn/home/hope-sesame-guangzhou/', 'Dongshankou', '58 Miaoqian Xijie', NULL, 'Guangzhou', 'Guangdong', 'CN', 23.12471, 113.28644, NULL),
    ('danicoparis', 'Danico', 'Cocktail bar from bartender Nico de Soto at the back of the Italian restaurant Daroco, in a former Jean Paul Gaultier store in Galerie Vivienne. Known for conceptual menus, including a series in which each list explored a different country. Walk-in only. No. 30 on The World''s 50 Best Bars 2025.', 'https://daroco.com/#danico', '2nd arrondissement', '6 Rue Vivienne', '75002', 'Paris', 'Île-de-France', 'FR', 48.86712, 2.33929, NULL),
    ('scarfesbar', 'Scarfes Bar', 'Hotel bar at Rosewood London named after caricaturist Gerald Scarfe, whose drawings line the walls and shape the menus. Velvet armchairs, an open fire, shelves of antique books and live music every night set the tone. No. 31 on The World''s 50 Best Bars 2025.', 'https://scarfesbar.com/', 'Holborn', '252 High Holborn', 'WC1V 7EN', 'London', NULL, 'GB', 51.51757, -0.11813, NULL),
    ('svanen.oslo', 'Svanen', 'Cocktail bar in Svaneapoteket, an 1896 pharmacy on Karl Johans gate whose mahogany and marble interior is protected as cultural heritage. Its modern drinks take cues from the botanicals named on the old apothecary drawers. No. 32 on The World''s 50 Best Bars 2025.', 'https://www.svanenoslo.no/', 'Sentrum', 'Karl Johans gate 13', '0154', 'Oslo', NULL, 'NO', 59.91237, 10.74479, NULL),
    ('sastreriamartinezlima', 'Sastrería Martinez', 'Speakeasy in Miraflores reached through the front of a tailor''s shop, styled on the 1920s. Head bartender Diego Macedo builds the menu around Peruvian ingredients from the coast, the Andes and the Amazon. No. 33 on The World''s 50 Best Bars 2025.', 'https://www.sastreriamartinez.com/', 'Miraflores', 'Av. Mariscal La Mar 1263', '15074', 'Lima', 'Lima', 'PE', -12.10998, -77.04902, NULL),
    ('pandaandsons', 'Panda & Sons', 'Basement bar on Queen Street entered through a vintage barbershop front, owned by Iain McPherson. It is known for sub-zero techniques such as freeze distillation and freeze drying, used in both classics and frozen dessert-style drinks. No. 34 on The World''s 50 Best Bars 2025.', 'https://pandaandsons.com/', 'New Town', '79 Queen Street', 'EH2 4NF', 'Edinburgh', NULL, 'GB', 55.95321, -3.20697, NULL),
    ('rodahusetsthlm', 'Röda Huset', 'Restaurant and bar in a red house above Sergels torg, opened by Hampus Thunholm in 2021. Upstairs, an 18-seat cocktail room serves a Scandinavian tasting menu of drinks built on Swedish produce such as plums, raspberries and whey. No. 35 on The World''s 50 Best Bars 2025.', 'https://rodahuset.nu/', 'Norrmalm', 'Malmskillnadsgatan 9', '111 57', 'Stockholm', NULL, 'SE', 59.33268, 18.06617, NULL),
    ('mimikakushi', 'Mimi Kakushi', 'Japanese restaurant and bar at the Four Seasons Resort on Jumeirah Beach, themed on 1920s Osaka when jazz and Western fashion reached Japan. Its best-known drink is a martini served frozen inside a block of ice carved at the table. No. 36 on The World''s 50 Best Bars 2025.', 'https://mimikakushi.ae/', 'Jumeirah', 'Restaurant Village, Four Seasons Resort Dubai at Jumeirah Beach, Jumeirah Beach Road', NULL, 'Dubai', 'Dubai', 'AE', 25.20266, 55.24073, NULL),
    ('salmonguru', 'Salmon Guru', 'Cocktail bar opened in 2016 by Argentine bartender Diego Cabrera, with the motto ''always against the flow''. Several themed rooms, a playful menu developed at his nearby lab, and sister bars in Dubai and Milan. No. 37 on The World''s 50 Best Bars 2025.', 'https://salmonguru.es/', 'Barrio de las Letras', 'Calle de Echegaray 21', '28014', 'Madrid', 'Madrid', 'ES', 40.4149, -3.69953, NULL),
    ('coahongkong', 'COA', 'Agave bar opened in 2017 by Jay Khan and named after the blade used to harvest agave. Inspired by Mexican drinking dens, it pairs Mexican-inflected cocktails with a deep list of tequila, mezcal, raicilla and sotol. No. 38 on The World''s 50 Best Bars 2025.', 'https://coa.com.hk/', 'Central', 'Shop A, LG/F, Wah Shin House, 6-10 Shin Hing Street', NULL, 'Hong Kong', NULL, 'HK', 22.28402, 114.15206, NULL),
    ('sipandguzzlenyc', 'Sip & Guzzle', 'Two-level West Village bar from Shingo Gokan and Steve Schneider. Upstairs, Guzzle is the lively room led by Schneider; downstairs, Sip is a smaller, more intimate bar led by Gokan, with food by chef Mike Bagale. No. 39 on The World''s 50 Best Bars 2025.', 'https://www.sipandguzzlenyc.com/', 'West Village', '29 Cornelia Street', '10014', 'New York', 'NY', 'US', 40.73141, -74.00245, NULL),
    ('drinkkongbar', 'Drink Kong', 'Monti bar from Patrick Pistolesi with a neon-lit, retro-futurist look drawing on Japanese design. The menu centres on pared-back neoclassic cocktails, such as a Japanese whisky drink with miso cordial. No. 40 on The World''s 50 Best Bars 2025.', 'https://www.drinkkong.com/', 'Monti', 'Piazza di San Martino ai Monti 8', '00184', 'Rome', 'Lazio', 'IT', 41.89514, 12.49787, NULL),
    ('doublechickenpleasenyc', 'Double Chicken Please', 'Lower East Side bar from Taiwanese bartenders GN Chan and Faye Chen, split into Free Range, a front room pouring kegged cocktails, and The Coop, a back room whose drinks are built to taste like dishes, served with Taiwanese inspired snacks. No. 41 on The World''s 50 Best Bars 2025.', 'https://doublechickenplease.com/', 'Lower East Side', '115 Allen Street', '10002', 'New York', 'NY', 'US', 40.71958, -73.99049, NULL),
    ('maybe_sammy_sydney', 'Maybe Sammy', 'Cocktail bar in The Rocks styled as a 1950s hotel bar without the hotel, all pink velvet and old Hollywood glamour. Opened in 2019 by Stefano Catino, Vince Lombardo and Andrea Gualdi, the team behind Maybe Frank. No. 42 on The World''s 50 Best Bars 2025.', 'https://www.maybesammy.com/', 'The Rocks', '115 Harrington Street', '2000', 'Sydney', 'NSW', 'AU', -33.86171, 151.20691, NULL),
    ('1930cocktailbar', '1930', 'Milan speakeasy run by the Farmily Group (Flavio Angiolillo and partners) since 2013. Entry has traditionally come through a regular''s introduction or the group''s other bars, and the drinks list leans on culinary techniques and changes often. No. 43 on The World''s 50 Best Bars 2025.', 'https://www.farmilygroup.com/locali/1930', NULL, 'Via Edmondo De Amicis, 22', '20123', 'Milan', 'Lombardy', 'IT', 45.45871, 9.17829, NULL),
    ('jewelnola', 'Jewel of the South', 'French Quarter tavern in an 1830s Creole cottage with a courtyard, co-founded by bartender Chris Hannah. Named after the 19th century bar of Joseph Santini, credited with the Brandy Crusta, it pairs classic New Orleans cocktails with a full kitchen. No. 44 on The World''s 50 Best Bars 2025.', 'https://www.jewelnola.com/', 'French Quarter', '1026 St. Louis Street', '70112', 'New Orleans', 'LA', 'US', 29.95856, -90.06948, NULL),
    ('virtutokyo', 'Virtù', 'Art Deco bar on the 39th floor of Four Seasons Hotel Tokyo at Otemachi, mixing Parisian style with Japanese technique. Led by head bartender Keith Motsi, its story-led menu draws on Japanese tales and European fables, backed by vintage French spirits. No. 45 on The World''s 50 Best Bars 2025.', 'https://www.fourseasons.com/otemachi/dining/restaurants/virtu/', 'Otemachi', '1-2-1 Otemachi, 39F', '100-0004', 'Tokyo', 'Tokyo', 'JP', 35.68775, 139.7633, NULL),
    ('overstory', 'Overstory', 'Cocktail bar on the 64th floor of the Art Deco 70 Pine Street, one floor above Saga, with a wraparound terrace and views over Manhattan. Guests ride a private elevator and climb a travertine stair to reach it. No. 46 on The World''s 50 Best Bars 2025.', 'https://www.overstory-nyc.com/', 'Financial District', '70 Pine Street, 64th Floor', '10005', 'New York', 'NY', 'US', 40.70647, -74.00774, NULL),
    ('the.bar.in.front.of.the.bar', 'The Bar in Front of the Bar', 'Street-side counter on pedestrian Petraki Street, opened in 2021 by Alexandros Tselepis, Konstantinos Theodorakopoulos and Simeon Papanikolaou. The short list changes daily, is made from scratch in their lab, and a big sign out front flashes jokey messages. No. 47 on The World''s 50 Best Bars 2025.', 'https://thebarinfrontofthebar.gr/', 'Syntagma', 'Petraki 1', '105 63', 'Athens', 'Attica', 'GR', 37.97556, 23.73228, NULL),
    ('the_bellwood', 'The Bellwood', 'Shibuya bar opened in 2020 by Atsushi Suzuki, formerly of Speak Low in Shanghai, styled after Taisho era cafe bars with stained glass and wood relief. Drinks are served as a kaiseki-like progression, with a sushi counter, Belle Sushi, at the back. No. 48 on The World''s 50 Best Bars 2025.', 'https://www.instagram.com/the_bellwood/', 'Shibuya', '41-31 Udagawacho', '150-0042', 'Tokyo', 'Tokyo', 'JP', 35.66308, 139.69501, NULL),
    ('bkksocialclub', 'BKK Social Club', 'Glamorous bar inside Four Seasons Hotel Bangkok at Chao Phraya River, with arches, a mirrored back bar and greenery, opened in 2020 and led by Berlin-born Philip Bischoff. Its drinks lists take cues from Latin America, most recently Mexico City. No. 49 on The World''s 50 Best Bars 2025.', 'https://www.fourseasons.com/bangkok/dining/lounges/bkk-social-club/', 'Charoen Krung', '300/1 Charoen Krung Road', '10120', 'Bangkok', NULL, 'TH', 13.71143, 100.51022, NULL),
    ('nutmegandclove', 'Nutmeg & Clove', 'Bar and restaurant founded in 2014 by Colin Chia that builds its cocktails and modern Singaporean plates around the island''s history and flavours. Now in a Purvis Street shophouse, on the street where Chia''s family once lived. No. 50 on The World''s 50 Best Bars 2025.', 'https://www.nutmegclove.com/', 'Bugis', '8 Purvis Street', '188587', 'Singapore', NULL, 'SG', 1.29678, 103.85515, NULL)
) AS v("handle", "name", "bio", "website", "locality", "address_line", "postcode", "city", "region", "country_code",
       "latitude", "longitude", "venue_slug")
LEFT JOIN "public"."bars" b ON b.slug = v.venue_slug
-- A venue that already has its profile keeps it.
WHERE NOT EXISTS (SELECT 1 FROM "public"."profiles" p WHERE p.bar_id = b.id)
  -- Nor a second copy of a bar someone already added (add_venue's rule).
  AND NOT EXISTS (
    SELECT 1 FROM "public"."profiles" p
    WHERE p.kind = 'bar' AND p.latitude BETWEEN v.latitude - 0.002 AND v.latitude + 0.002
      AND private.venue_name_key(p.display_name) = private.venue_name_key(v.name)
      AND private.distance_km(v.latitude, v.longitude, p.latitude, p.longitude) <= 0.15
  )
ON CONFLICT ("handle") DO NOTHING;
