-- Local and national bar awards for bars already on the map: 189 rows.
--
-- The World's and regional 50 Best lists are global. These are the awards
-- each city's own bar scene watches: the UK's Top 50 Cocktail Bars, Time Out's
-- food and drink awards in Sydney, Melbourne, Hong Kong and Paris, Mexico's
-- Shaker Awards, Bangkok's Bar Show and BK Magazine's BAD Awards, Tatler Best,
-- and one James Beard Outstanding Bar. Rows by body:
--   Top 50 Cocktail Bars: 105
--   Shaker Awards: 37
--   Time Out Hong Kong Bar Awards: 17
--   Bangkok Bar Show Awards: 13
--   BAD Awards: 7
--   Time Out Melbourne Food & Drink Awards: 3
--   Time Out Paris Food & Drink Awards: 3
--   Time Out Sydney Food & Drink Awards: 2
--   James Beard Awards: 1
--   Tatler Best: 1
--
-- Rules, same as the earlier award seeds: winners and list places only (no
-- shortlists), no sponsor names in the body or the title, the title as the
-- body writes it (French and Spanish kept), person awards left out. Each row
-- links the page that names the bar and the award, checked 29-30 Sep 2026.
-- Rows join on the bar's handle, so a bar that isn't here is skipped, and a
-- row already present (same bar, body, year and title) is left alone.
--
-- Left out on purpose: Top 500 Bars (global, thin sourcing), Good Food Guide
-- hats (not verifiable from the guide itself), and Gourmet Traveller (its bar
-- award went to bars we don't list).

INSERT INTO "public"."profile_awards" ("profile_id", "award", "year", "position", "title", "source_url")
SELECT p.id, v.award, v.year::smallint, v.position::smallint, v.title::text, v.source_url
FROM (VALUES
    ('bar.us.bkk', 'BAD Awards', 2026, NULL, 'Bar of the Year', 'https://badawards.bkmagazine.com/bars-of-the-year/bad-awards-bar-of-the-year-for-2026/'),
    ('bkksocialclub', 'BAD Awards', 2025, NULL, 'Best Hotel Bar', 'https://badawards.bkmagazine.com/bar-winners/winners-list-for-the-bad-awards-2025/'),
    ('bkksocialclub', 'BAD Awards', 2026, NULL, 'Best Hotel Bar', 'https://badawards.bkmagazine.com/hotel-bars/best-hotel-bars-in-bangkok-for-2026/'),
    ('drywavecocktailstudio', 'BAD Awards', 2025, NULL, 'Bar of the Year', 'https://badawards.bkmagazine.com/bar-winners/winners-list-for-the-bad-awards-2025/'),
    ('drywavecocktailstudio', 'BAD Awards', 2025, NULL, 'Best New Bar', 'https://badawards.bkmagazine.com/bar-winners/winners-list-for-the-bad-awards-2025/'),
    ('drywavecocktailstudio', 'BAD Awards', 2026, NULL, 'Best Cocktail Bar', 'https://badawards.bkmagazine.com/cocktail-bars/best-cocktail-bars-in-bangkok-for-2026/'),
    ('opm.bkk', 'BAD Awards', 2025, NULL, 'Best Cocktail Bar', 'https://badawards.bkmagazine.com/bar-winners/winners-list-for-the-bad-awards-2025/'),
    ('bar.us.bkk', 'Bangkok Bar Show Awards', 2025, 2, NULL, 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('bkksocialclub', 'Bangkok Bar Show Awards', 2025, NULL, 'Art of Hospitality', 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('bkksocialclub', 'Bangkok Bar Show Awards', 2025, NULL, 'Hotel Bar of the Year', 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('drywavecocktailstudio', 'Bangkok Bar Show Awards', 2025, NULL, 'Bar Team of the Year', 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('drywavecocktailstudio', 'Bangkok Bar Show Awards', 2025, NULL, 'Best Bar in Bangkok', 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('drywavecocktailstudio', 'Bangkok Bar Show Awards', 2025, NULL, 'Best Bar in Thailand', 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('drywavecocktailstudio', 'Bangkok Bar Show Awards', 2025, NULL, 'Menu Design of the Year', 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('drywavecocktailstudio', 'Bangkok Bar Show Awards', 2025, 1, NULL, 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('god_bkk', 'Bangkok Bar Show Awards', 2025, 3, NULL, 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('mahaniyom.cocktailbar', 'Bangkok Bar Show Awards', 2025, 13, NULL, 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('opm.bkk', 'Bangkok Bar Show Awards', 2025, 4, NULL, 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('tropiccitybkk', 'Bangkok Bar Show Awards', 2025, 5, NULL, 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('vesperbkk', 'Bangkok Bar Show Awards', 2025, 7, NULL, 'https://thedotmagazine.com/thailands-best-bars-revealed-in-the-bangkok-bar-show-awards-2025/'),
    ('barkumiko', 'James Beard Awards', 2025, NULL, 'Outstanding Bar', 'https://www.jamesbeard.org/stories/the-2025-james-beard-award-winners'),
    ('3monosbar', 'Shaker Awards', 2025, NULL, 'Mejor bar de Latinoamérica', 'https://www.eluniversal.com.mx/menu/los-30-mejores-bares-de-mexico-segun-shaker-awards-2025/'),
    ('alquimicocartagena', 'Shaker Awards', 2023, NULL, 'Mejor Bar del Mundo', 'https://shakerawards.com/awards/awards2023/'),
    ('arcatulum', 'Shaker Awards', 2023, 6, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('arcatulum', 'Shaker Awards', 2024, 4, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('arcatulum', 'Shaker Awards', 2025, 7, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('baltrabar', 'Shaker Awards', 2023, 12, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('baltrabar', 'Shaker Awards', 2024, 12, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('barmauromx', 'Shaker Awards', 2025, 1, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('brujasmex', 'Shaker Awards', 2023, 14, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('brujasmex', 'Shaker Awards', 2024, 22, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('elgalloaltanero', 'Shaker Awards', 2023, 9, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('elgalloaltanero', 'Shaker Awards', 2024, 6, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('elgalloaltanero', 'Shaker Awards', 2025, 28, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('fomabar.mx', 'Shaker Awards', 2025, NULL, 'Mejor Team Bar', 'https://www.eluniversal.com.mx/menu/los-30-mejores-bares-de-mexico-segun-shaker-awards-2025/'),
    ('fomabar.mx', 'Shaker Awards', 2025, 10, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('handshake_bar', 'Shaker Awards', 2023, 1, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('handshake_bar', 'Shaker Awards', 2024, 1, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('handshake_bar', 'Shaker Awards', 2025, 3, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('hankypankydf', 'Shaker Awards', 2023, 3, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('hankypankydf', 'Shaker Awards', 2024, 8, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('hankypankydf', 'Shaker Awards', 2025, 22, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('kaitodelvalle', 'Shaker Awards', 2023, 8, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('kaitodelvalle', 'Shaker Awards', 2024, 7, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('kaitodelvalle', 'Shaker Awards', 2025, 5, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('limantourmx', 'Shaker Awards', 2023, 2, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('limantourmx', 'Shaker Awards', 2024, 15, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('limantourmx', 'Shaker Awards', 2025, 9, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('rayocdmx', 'Shaker Awards', 2023, 13, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('rayocdmx', 'Shaker Awards', 2024, 28, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('superbuenonyc', 'Shaker Awards', 2025, NULL, 'Mejor bar de Norteamérica', 'https://www.eluniversal.com.mx/menu/los-30-mejores-bares-de-mexico-segun-shaker-awards-2025/'),
    ('tlecan', 'Shaker Awards', 2023, 20, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('tlecan', 'Shaker Awards', 2024, 2, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('tlecan', 'Shaker Awards', 2025, 2, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('zapotebar', 'Shaker Awards', 2023, 4, NULL, 'https://shakerawards.com/top-30/top2023/'),
    ('zapotebar', 'Shaker Awards', 2024, 3, NULL, 'https://shakerawards.com/top-30/top2024/'),
    ('zapotebar', 'Shaker Awards', 2025, NULL, 'Mejor bar de hotel de México', 'https://www.eluniversal.com.mx/menu/los-30-mejores-bares-de-mexico-segun-shaker-awards-2025/'),
    ('zapotebar', 'Shaker Awards', 2025, 6, NULL, 'https://shakerawards.com/top-30/top2025/'),
    ('barleonehk', 'Tatler Best', 2025, NULL, 'Bar of the Year, Asia-Pacific', 'https://tatlergroup.com/news-articles/tatler-best-awards-2025-concludes-with-a-glamorous-gala-dinner-celebrating-hospitalitys-best-in-class-across-asia-pacific-and-the-middle-east'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2021, NULL, 'Best Cocktail Programme', 'https://www.timeout.com/hong-kong/bar-awards-2021-winners'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2021, NULL, 'Best New Bar', 'https://www.timeout.com/hong-kong/bar-awards-2021-winners'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2021, NULL, 'Readers'' Choice', 'https://www.timeout.com/hong-kong/bar-awards-2021-winners'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2023, NULL, 'Bar of the Year', 'https://www.timeout.com/hong-kong/bar-awards-2022-winners'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2023, NULL, 'Best Hotel Bar', 'https://www.timeout.com/hong-kong/bar-awards-2022-winners'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2023, NULL, 'Readers'' Choice', 'https://www.timeout.com/hong-kong/bar-awards-2022-winners'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2024, NULL, 'Bar Congeniality', 'https://www.timeout.com/hong-kong/bar-awards-2024-winners'),
    ('argobarhk', 'Time Out Hong Kong Bar Awards', 2024, NULL, 'Best Innovative Bar', 'https://www.timeout.com/hong-kong/bar-awards-2024-winners'),
    ('barleonehk', 'Time Out Hong Kong Bar Awards', 2024, NULL, 'Bar of the Year', 'https://www.timeout.com/hong-kong/bar-awards-2024-winners'),
    ('darksidehk', 'Time Out Hong Kong Bar Awards', 2021, NULL, 'Best Bar', 'https://www.timeout.com/hong-kong/bar-awards-2021-winners'),
    ('darksidehk', 'Time Out Hong Kong Bar Awards', 2021, NULL, 'Best Hotel Bar', 'https://www.timeout.com/hong-kong/bar-awards-2021-winners'),
    ('darksidehk', 'Time Out Hong Kong Bar Awards', 2023, NULL, 'Best Cocktail Programme', 'https://www.timeout.com/hong-kong/bar-awards-2022-winners'),
    ('darksidehk', 'Time Out Hong Kong Bar Awards', 2023, NULL, 'Best Sustainable Cocktail', 'https://www.timeout.com/hong-kong/bar-awards-2022-winners'),
    ('kinsman.hk', 'Time Out Hong Kong Bar Awards', 2024, NULL, 'Spirit of Hong Kong', 'https://www.timeout.com/hong-kong/bar-awards-2024-winners'),
    ('penicillin_bar', 'Time Out Hong Kong Bar Awards', 2021, NULL, 'Best Sustainability Initiative', 'https://www.timeout.com/hong-kong/bar-awards-2021-winners'),
    ('quinaryhk', 'Time Out Hong Kong Bar Awards', 2024, NULL, 'Timeless Bar', 'https://www.timeout.com/hong-kong/bar-awards-2024-winners'),
    ('thesavoryproject', 'Time Out Hong Kong Bar Awards', 2024, NULL, 'Rising Star', 'https://www.timeout.com/hong-kong/bar-awards-2024-winners'),
    ('aboveboardbarmelb', 'Time Out Melbourne Food & Drink Awards', 2022, NULL, 'Best Cocktail Bar', 'https://www.timeout.com/melbourne/time-out-food-drink-awards-cocktail-bar'),
    ('bar.bellamy', 'Time Out Melbourne Food & Drink Awards', 2025, NULL, 'Best Cocktail Bar', 'https://www.timeout.com/melbourne/news/the-winners-of-time-out-melbournes-food-drink-awards-2025-have-been-revealed-031725'),
    ('caretakers.cottage', 'Time Out Melbourne Food & Drink Awards', 2025, NULL, 'Bar of the Year', 'https://www.timeout.com/melbourne/news/the-winners-of-time-out-melbournes-food-drink-awards-2025-have-been-revealed-031725'),
    ('barnouveau', 'Time Out Paris Food & Drink Awards', 2024, NULL, 'Meilleur bar à cocktails', 'https://www.lhotellerie-restauration.fr/actualite/time-out-paris-devoile-le-palmares-des-food-drink-awards'),
    ('devie.bar', 'Time Out Paris Food & Drink Awards', 2025, NULL, 'Meilleur bar à cocktails', 'https://www.timeout.fr/paris/actualites/le-palmares-des-time-out-paris-food-drink-awards-2025-042925'),
    ('littlereddoor_paris', 'Time Out Paris Food & Drink Awards', 2023, NULL, 'Meilleure carte de cocktails', 'https://www.lhotellerie-restauration.fr/actualite/les-premiers-laureats-des-time-out-paris-food-drink-awards'),
    ('deanandnancyon22', 'Time Out Sydney Food & Drink Awards', 2022, NULL, 'Best Cocktail Bar', 'https://www.timeout.com/sydney/bars/time-out-food-drink-awards-2022-best-cocktail-bar'),
    ('re.sydney', 'Time Out Sydney Food & Drink Awards', 2023, NULL, 'Best Innovation', 'https://cocktailsandbars.com/time-out-sydney-food-drink-awards-2023/'),
    ('69colebrookerow', 'Top 50 Cocktail Bars', 2024, 36, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('69colebrookerow', 'Top 50 Cocktail Bars', 2025, 50, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('abarwithshapesforaname', 'Top 50 Cocktail Bars', 2022, 11, NULL, 'https://confidentials.com/manchester/top-50-cocktail-bars-2022-revealed'),
    ('abarwithshapesforaname', 'Top 50 Cocktail Bars', 2023, 9, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('abarwithshapesforaname', 'Top 50 Cocktail Bars', 2024, 14, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('abarwithshapesforaname', 'Top 50 Cocktail Bars', 2025, 35, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('abarwithshapesforaname', 'Top 50 Cocktail Bars', 2026, 36, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('amarobarlondon', 'Top 50 Cocktail Bars', 2023, 46, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('amarobarlondon', 'Top 50 Cocktail Bars', 2024, NULL, 'Highest Climber', 'https://www.morningadvertiser.co.uk/Article/2024/02/07/Where-are-the-UK-s-Top-50-Cocktail-Bars-for-2024/'),
    ('amarobarlondon', 'Top 50 Cocktail Bars', 2024, 8, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('amarobarlondon', 'Top 50 Cocktail Bars', 2025, 14, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('amarobarlondon', 'Top 50 Cocktail Bars', 2026, 7, NULL, 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/'),
    ('americanbargleneagles', 'Top 50 Cocktail Bars', 2024, 50, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('americanbargleneagles', 'Top 50 Cocktail Bars', 2025, 37, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('americanbargleneagles', 'Top 50 Cocktail Bars', 2026, 50, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('americanbarsavoy', 'Top 50 Cocktail Bars', 2022, 15, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('artesianbar', 'Top 50 Cocktail Bars', 2022, 19, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('artesianbar', 'Top 50 Cocktail Bars', 2023, 17, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('artesianbar', 'Top 50 Cocktail Bars', 2024, 37, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('bramble_bar', 'Top 50 Cocktail Bars', 2022, 6, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('bramble_bar', 'Top 50 Cocktail Bars', 2024, 32, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('bramble_bar', 'Top 50 Cocktail Bars', 2025, 36, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('calloohcallaybar', 'Top 50 Cocktail Bars', 2022, 48, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('calloohcallaybar', 'Top 50 Cocktail Bars', 2023, 37, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('calloohcallaybar', 'Top 50 Cocktail Bars', 2024, 38, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('calloohcallaybar', 'Top 50 Cocktail Bars', 2025, 48, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('connaughtbar', 'Top 50 Cocktail Bars', 2022, 3, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('connaughtbar', 'Top 50 Cocktail Bars', 2023, 10, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('connaughtbar', 'Top 50 Cocktail Bars', 2024, 20, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('connaughtbar', 'Top 50 Cocktail Bars', 2025, 20, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('connaughtbar', 'Top 50 Cocktail Bars', 2026, 31, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('coupettelondon', 'Top 50 Cocktail Bars', 2022, 18, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('coupettelondon', 'Top 50 Cocktail Bars', 2023, 31, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('happiness_hoxton', 'Top 50 Cocktail Bars', 2022, 23, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('happiness_hoxton', 'Top 50 Cocktail Bars', 2023, 26, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('happiness_hoxton', 'Top 50 Cocktail Bars', 2024, 34, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('happiness_hoxton', 'Top 50 Cocktail Bars', 2025, 47, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('happiness_hoxton', 'Top 50 Cocktail Bars', 2026, 44, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('kwantmayfair', 'Top 50 Cocktail Bars', 2024, NULL, 'Highest New Entry', 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('kwantmayfair', 'Top 50 Cocktail Bars', 2024, 11, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('kwantmayfair', 'Top 50 Cocktail Bars', 2025, 31, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('kwantmayfair', 'Top 50 Cocktail Bars', 2026, 19, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('lab22cardiff', 'Top 50 Cocktail Bars', 2022, 1, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('lab22cardiff', 'Top 50 Cocktail Bars', 2023, 2, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('lab22cardiff', 'Top 50 Cocktail Bars', 2024, 17, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('lab22cardiff', 'Top 50 Cocktail Bars', 2025, 26, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('lab22cardiff', 'Top 50 Cocktail Bars', 2026, NULL, 'Bar Team of the Year', 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/'),
    ('lab22cardiff', 'Top 50 Cocktail Bars', 2026, 24, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('lyanessbar', 'Top 50 Cocktail Bars', 2022, 31, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('lyanessbar', 'Top 50 Cocktail Bars', 2023, 23, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('lyanessbar', 'Top 50 Cocktail Bars', 2024, 47, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('lyanessbar', 'Top 50 Cocktail Bars', 2025, 10, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('lyanessbar', 'Top 50 Cocktail Bars', 2026, 25, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('nightjar', 'Top 50 Cocktail Bars', 2022, 13, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('nightjar', 'Top 50 Cocktail Bars', 2023, 19, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('nightjar', 'Top 50 Cocktail Bars', 2024, 44, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('pandaandsons', 'Top 50 Cocktail Bars', 2022, 9, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('pandaandsons', 'Top 50 Cocktail Bars', 2023, 6, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('pandaandsons', 'Top 50 Cocktail Bars', 2024, 9, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('pandaandsons', 'Top 50 Cocktail Bars', 2025, 2, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('pandaandsons', 'Top 50 Cocktail Bars', 2026, 9, NULL, 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/'),
    ('satans_whiskers', 'Top 50 Cocktail Bars', 2022, 5, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('satans_whiskers', 'Top 50 Cocktail Bars', 2023, 1, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('satans_whiskers', 'Top 50 Cocktail Bars', 2024, 2, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('satans_whiskers', 'Top 50 Cocktail Bars', 2025, 1, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('satans_whiskers', 'Top 50 Cocktail Bars', 2026, 3, NULL, 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/'),
    ('scarfesbar', 'Top 50 Cocktail Bars', 2022, 20, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('scarfesbar', 'Top 50 Cocktail Bars', 2023, 22, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('scarfesbar', 'Top 50 Cocktail Bars', 2024, 33, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('scarfesbar', 'Top 50 Cocktail Bars', 2025, 32, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('scarfesbar', 'Top 50 Cocktail Bars', 2026, 35, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('schofields.bar', 'Top 50 Cocktail Bars', 2022, 16, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('schofields.bar', 'Top 50 Cocktail Bars', 2023, 4, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('schofields.bar', 'Top 50 Cocktail Bars', 2024, 1, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('schofields.bar', 'Top 50 Cocktail Bars', 2025, 3, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('schofields.bar', 'Top 50 Cocktail Bars', 2026, 6, NULL, 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/'),
    ('sidehustlelondon', 'Top 50 Cocktail Bars', 2024, 24, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('sidehustlelondon', 'Top 50 Cocktail Bars', 2025, 34, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('sidehustlelondon', 'Top 50 Cocktail Bars', 2026, 12, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('swiftsoho', 'Top 50 Cocktail Bars', 2022, 2, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('swiftsoho', 'Top 50 Cocktail Bars', 2023, 5, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('swiftsoho', 'Top 50 Cocktail Bars', 2024, 7, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('swiftsoho', 'Top 50 Cocktail Bars', 2025, 6, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('swiftsoho', 'Top 50 Cocktail Bars', 2026, 15, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('tayer_elementary', 'Top 50 Cocktail Bars', 2022, NULL, 'Highest New Entry', 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('tayer_elementary', 'Top 50 Cocktail Bars', 2022, 4, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('tayer_elementary', 'Top 50 Cocktail Bars', 2023, 3, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('tayer_elementary', 'Top 50 Cocktail Bars', 2024, 10, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('tayer_elementary', 'Top 50 Cocktail Bars', 2025, 5, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('tayer_elementary', 'Top 50 Cocktail Bars', 2026, 10, NULL, 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/'),
    ('terminisoho', 'Top 50 Cocktail Bars', 2022, 38, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('terminisoho', 'Top 50 Cocktail Bars', 2023, 33, NULL, 'https://www.hot-dinners.com/2023020812112/Gastroblog/Latest-news/top-50-cocktail-bars-list-2023'),
    ('terminisoho', 'Top 50 Cocktail Bars', 2024, 29, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('terminisoho', 'Top 50 Cocktail Bars', 2025, 21, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('terminisoho', 'Top 50 Cocktail Bars', 2026, 8, NULL, 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/'),
    ('theoriolebar', 'Top 50 Cocktail Bars', 2022, 8, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('threesheetsbars', 'Top 50 Cocktail Bars', 2022, 7, NULL, 'https://www.morningadvertiser.co.uk/Article/2022/02/02/top-50-cocktail-bars-in-the-uk-2022/'),
    ('threesheetsbars', 'Top 50 Cocktail Bars', 2023, 7, NULL, 'https://www.morningadvertiser.co.uk/Article/2023/02/08/Where-are-the-Top-50-Cocktail-Bars-in-the-UK/'),
    ('threesheetsbars', 'Top 50 Cocktail Bars', 2024, 13, NULL, 'https://www.hot-dinners.com/2024020712974/Gastroblog/Latest-news/top-50-cocktail-bars-2024-list-london'),
    ('threesheetsbars', 'Top 50 Cocktail Bars', 2025, 13, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('threesheetsbars', 'Top 50 Cocktail Bars', 2026, 32, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('threesheetssoho', 'Top 50 Cocktail Bars', 2026, 11, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('viajantebar', 'Top 50 Cocktail Bars', 2025, 17, NULL, 'https://www.timeout.com/uk/news/the-uks-top-50-cocktail-bars-have-been-crowned-for-2025-full-list-of-award-winning-bars-021225'),
    ('viajantebar', 'Top 50 Cocktail Bars', 2026, 33, NULL, 'https://www.top50cocktailbars.com/list/1-50'),
    ('waltzbar', 'Top 50 Cocktail Bars', 2026, 5, NULL, 'https://www.morningadvertiser.co.uk/Article/2026/02/10/couch-in-stirchley-west-midlands-named-number-one-on-top-50-cocktail-bars-2026-list/')
) AS v ("handle", "award", "year", "position", "title", "source_url")
JOIN "public"."profiles" p ON p.handle = v.handle AND p.kind = 'bar'
ON CONFLICT DO NOTHING;
