import type { Equipment, EquipmentKind } from './types';

export const EQUIPMENT_KINDS: { id: EquipmentKind; name: string }[] = [
  { id: 'bar', name: 'Bar tools' },
  { id: 'measure', name: 'Measure' },
  { id: 'mix', name: 'Blend and whip' },
  { id: 'pressure', name: 'Gas and vacuum' },
  { id: 'temperature', name: 'Heat and cold' },
  { id: 'separate', name: 'Strain and spin' },
  { id: 'specialist', name: 'Specialist' },
];

/**
 * The kit techniques call for. Pots, jars, fine strainers, coffee filters, a
 * fridge and a freezer are assumed, so they aren't listed. Prices are only
 * given where a source gave one; tiers elsewhere are our estimate. Buy links
 * go to the maker or a specialist shop, checked October 2026, with no
 * tracking or affiliate codes.
 */
export const EQUIPMENT: Equipment[] = [
  { id: 'shaker', name: 'Shaker tins', kind: 'bar', tier: '$', what: 'Tin-on-tin shaking: chills, dilutes and airs a sour fast.', buy: [{ name: 'Koriko weighted tins, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/set-of-koriko-weighted-shaking-tins-stainless-steel' }] },
  { id: 'jigger', name: 'Jigger', kind: 'bar', tier: '$', what: 'The same pour every time, whoever is behind the bar.', note: 'Check it against a scale once: water weighs 1 g per ml.', buy: [{ name: 'Japanese-style jigger 1 oz and 2 oz, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/japanese-style-jigger-1oz-2oz-stainless-steel' }] },
  { id: 'mixing-glass', name: 'Mixing glass and bar spoon', kind: 'bar', tier: '$', what: 'Stirred drinks: chilled and diluted without the air and cloud of a shake.', swap: 'The bigger shaker tin.', buy: [{ name: 'Yarai mixing glass 500 ml, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/yarai-mixing-glass-500ml-17oz' }, { name: 'Teardrop bar spoon 30 cm, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/teardrop-barspoon-stainless-steel-30cm' }] },
  { id: 'strainers', name: 'Hawthorne and julep strainers', kind: 'bar', tier: '$', what: 'The Hawthorne holds ice back from a tin; the julep fits a mixing glass.', buy: [{ name: 'Koriko Hawthorne strainer, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/koriko-hawthorne-strainer-stainless-steel' }, { name: 'Julep strainer, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/premium-julep-strainer-stainless-steel-mirror-finish' }] },
  { id: 'citrus-press', name: 'Citrus press', kind: 'bar', tier: '$', what: 'Fresh lemon and lime for sours; a lever press keeps up with service.', note: 'Lime juice is best within a few hours of pressing.', buy: [{ name: 'Hamilton Beach 932 lever press, WebstaurantStore', url: 'https://www.webstaurantstore.com/hamilton-beach-932-commercial-citrus-juicer/410932.html' }, { name: 'FreshForce handheld press, Chef\'n', url: 'https://www.chefn.com/products/freshforce-citrus-juicer' }] },
  { id: 'peeler', name: 'Y-peeler and channel knife', kind: 'bar', tier: '$', what: 'Expressed peels, twists and long spirals.', note: 'Take the oily skin, not the bitter white pith.', buy: [{ name: 'Y-style citrus peeler, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/citrus-peeler-steel-plastic' }, { name: 'Channel knife, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/channel-knife-black-walnut-steel' }] },
  { id: 'ice-tools', name: 'Lewis bag, mallet and ice pick', kind: 'bar', tier: '$', what: 'Dry crushed ice for juleps and swizzles; cutting clear blocks into cubes.', swap: 'A tea towel and a rolling pin, for crushed ice.', note: 'Let a block temper a few minutes before you cut it, or it shatters.', buy: [{ name: 'Schmallet and Lewis bag, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/the-schmallet-and-lewis-bag' }, { name: 'Anvil ice pick, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/anvil-ice-pick-wood-and-stainless-steel' }] },
  { id: 'atomizer', name: 'Atomizer', kind: 'bar', tier: '$', what: 'An even mist of absinthe, peated whisky or bitters over a glass or a drink.', swap: 'Rinse the glass and pour out the rest.', buy: [{ name: 'Atomizer 50 ml, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/atomizer-aluminum-50ml-17oz' }, { name: 'Morgenthaler Triomphe atomizer, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/morgenthaler-triomphe-atomizer' }] },

  { id: 'scale-fine', name: 'Fine scale (0.01 g)', kind: 'measure', tier: '$', what: 'Weighs the gums, acids and foamers, which are mostly under a gram.', swap: 'Rough grams per 5 ml teaspoon: xanthan 3.5, agar 2.4, gellan 1.9, methylcellulose 1.3. Approximate only.', note: 'Get one that reads to 0.01 g with a 100 to 200 g top.', buy: [{ name: 'AWS Chrome 200 g x 0.01 g pocket scale, American Weigh Scales', url: 'https://awscales.com/aws-200-x-0-01g-chrome-pocket-scale/' }] },
  { id: 'scale', name: 'Kitchen scale', kind: 'measure', tier: '$', what: 'Weighs batches, sugar and juice. Syrups and ratios are by weight.', buy: [{ name: 'Escali Primo Professional 11 lb, WebstaurantStore', url: 'https://www.webstaurantstore.com/escali-scdgp11bk-primo-11-lb-black-and-silver-digital-portion-control-kitchen-scale/511SCDGP11BK.html' }, { name: 'Gravitas precision scale (0.1 g), ThermoWorks', url: 'https://www.thermoworks.com/products/gravitas' }] },
  { id: 'refractometer', name: 'Refractometer (Brix)', kind: 'measure', tier: '$$', what: 'Reads sugar in syrups, cordials and freeze-concentrated juice.', swap: 'Make syrups by weight and trust the ratio.', note: 'It reads all dissolved solids, so fruit syrups read a little high.', buy: [{ name: 'Atago PAL-1 digital, 0 to 53 Brix, Atago', url: 'https://atago-usa.com/PAL-1-p176.html' }, { name: 'Hanna HI96801 digital, 0 to 85 Brix, Hanna Instruments', url: 'https://hannainst.com/hi96801-digital-refractometer-for-brix-analysis.html' }, { name: 'Digital Brix meter, Modernist Pantry', url: 'https://modernistpantry.com/products/digital-sugar-brix-meter.html' }] },
  { id: 'ph', name: 'pH meter or strips', kind: 'measure', tier: '$$', what: 'Checks ferments, kombucha, acid-adjusted juice and spherification baths.', swap: 'Strips (under $20), for ferments.', note: 'Kombucha must finish at pH 4.2 or lower.', buy: [{ name: 'Apera PH60 pocket pH tester, Apera', url: 'https://aperainst.com/ph60-premium-waterproof-ph-tester-ph-meter-with-replaceable-probe-and-blacklight-apera-instruments' }, { name: 'Advanced pH meter, Modernist Pantry', url: 'https://modernistpantry.com/products/advanced-ph-meter.html' }, { name: 'Hydrion pH strips 0 to 14, Micro Essentials', url: 'https://www.microessentiallab.com/product/hydrion-9800-spectral-0-14-plastic-ph-strip' }] },
  { id: 'thermometer', name: 'Probe thermometer', kind: 'measure', tier: '$', what: 'Hydrating gums, gentle syrups, sous vide without a circulator, freezer checks.', buy: [{ name: 'Thermapen ONE, ThermoWorks', url: 'https://www.thermoworks.com/products/thermapen-one' }, { name: 'ThermoPop 2, ThermoWorks', url: 'https://www.thermoworks.com/products/thermopop-2' }] },
  { id: 'droppers', name: 'Dasher and dropper bottles', kind: 'measure', tier: '$', what: 'Saline, acid solutions, tinctures and foamer drops.', note: 'Write the strength on the label: "Saline 20%". A dash or drop isn’t a standard size.', buy: [{ name: 'Bitters bottle with steel dasher, 100 ml, Cocktail Kingdom', url: 'https://cocktailkingdom.com/products/bitters-bottle-stainless-steel-dasher-top-100ml-34oz' }, { name: '1 oz amber dropper bottle, Specialty Bottle', url: 'https://www.specialtybottle.com/glass-bottles/amber-boston-rounds/1oz-dropper-bra1d' }] },

  { id: 'stick-blender', name: 'Stick blender or milk frother', kind: 'mix', tier: '$', what: 'Lecithin airs, and getting gums into liquid without lumps.', swap: 'A whisk, slowly.', note: 'For an air, keep the head half out of the liquid in a wide container.', buy: [{ name: 'Control Grip immersion blender, Breville', url: 'https://www.breville.com/en-us/product/bsb510' }, { name: 'bamix M150 Mono, Sur La Table', url: 'https://www.surlatable.com/product/bamix-r-m150-mono-pro-deluxe-immersion-blender/9870627' }] },
  { id: 'blender', name: 'High-power blender', kind: 'mix', tier: '$$', what: 'Blender syrups, nut milks, fruit before enzymes, gums.', swap: 'A saucepan for syrups.', note: 'Friction heats the contents to about 77 °C in 5 minutes, so long blends cook the fruit.', buy: [{ name: 'The Quiet One bar blender, Vitamix', url: 'https://www.vitamix.com/us/en_us/products/commercial/the-quiet-one' }, { name: 'Drink Machine Advance, Vitamix', url: 'https://www.vitamix.com/us/en_us/products/commercial/drink-machine-advance' }, { name: '5200, Vitamix (home or small bar)', url: 'https://www.vitamix.com/us/en_us/products/5200-standard-getting-started' }] },
  { id: 'juicer', name: 'Juicer', kind: 'mix', tier: '$$', what: 'Fresh ginger, celery, apple and other juices for syrups and modifiers.', swap: 'Blend with a little water and strain through a superbag.', buy: [{ name: 'Juice Fountain Cold XL, Breville', url: 'https://www.breville.com/en-us/product/bje830' }, { name: 'X-1 Mini cold press (high volume), Goodnature', url: 'https://www.goodnature.com/juicers/x1-mini' }] },
  { id: 'stir-plate', name: 'Magnetic stirrer hot plate', kind: 'mix', tier: '$$', what: 'Hydrates gums and dissolves syrups and acids hands-free at a set heat.', swap: 'A pot, a thermometer and a whisk.', buy: [{ name: 'HSC-19T digital hotplate stirrer, TN Lab Supply', url: 'https://www.tnlab.com/products/magnetic-stirrer-hsc-19t-digital-display-ceramic-plate-rod' }] },
  { id: 'whipper', name: 'iSi whipper', kind: 'pressure', tier: '$', what: 'Siphon foams, fast nitrous infusions, and small batches of fizz with CO2.', swap: 'A shaker, for shaken foams only.', note: 'N2O cream chargers only, never past the fill line: 1 charger for 0.25 or 0.5 L, 2 for 1 L. Hold no hotter than 75 °C. Strain everything that goes in. Never open it under pressure.', buy: [{ name: 'iSi Gourmet Whip 1 L, WebstaurantStore', url: 'https://www.webstaurantstore.com/isi-1703-01-gourmet-whip-stainless-steel-whipped-cream-dispenser-1-liter/416170301.html' }, { name: 'iSi N2O chargers, 50 pack, WebstaurantStore', url: 'https://www.webstaurantstore.com/isi-076701-eco-series-professional-n20-charger-pack/416076701.html' }] },
  { id: 'co2-rig', name: 'CO2 carbonation rig', kind: 'pressure', tier: '$$', price: 'Under $200 for tank, regulator, line and caps', what: 'Force-carbonates cocktails, sodas and batches in PET bottles.', swap: 'An iSi with CO2 bulbs, for a few drinks.', note: 'Pressure-rated bottles only. 45 psi for cocktails, 60 for water.', buy: [{ name: '5 lb CO2 tank, MoreBeer', url: 'https://morebeer.com/products/5-lb-co2-tank-premium-aluminum-cga320-valve-dot-approved' }, { name: 'KOMOS dual-gauge regulator, 0 to 60 psi, MoreBeer', url: 'https://morebeer.com/products/komos-premium-dual-gauge-co2-regulator-industrialgrade-060-psi-operating-range-14-flare-fitting-barbed-outlet-duotight-adapter' }, { name: 'Stainless carbonation cap, MoreBeer', url: 'https://morebeer.com/products/carbonation-line-cleaning-ball-lock-quick-disconnect-qd-cap-stainless-duotight-compatible' }] },
  { id: 'chamber-vac', name: 'Chamber vacuum sealer', kind: 'pressure', tier: '$$', what: 'Vacuum infusion, compressed fruit, quick pickles, sealing liquids.', swap: 'A zip bag with the air pushed out under water.', note: 'An edge sealer can’t seal liquids. Use jars, not pouches, for spirits.', buy: [{ name: 'Avid Armor USV20, Avid Armor', url: 'https://avidarmor.com/products/avid-armor-ultra-series-usv20-chamber-vacuum-sealer-machine' }, { name: 'VacMaster VP215 (all-day use), WebstaurantStore', url: 'https://www.webstaurantstore.com/ary-vacmaster-vp215-chamber-vacuum-packaging-machine-with-10-1-4-seal-bar/120VMASVP215.html' }] },

  { id: 'sous-vide', name: 'Sous vide circulator', kind: 'temperature', tier: '$$', what: 'Infusions and syrups at an exact temperature.', swap: 'A pot and a thermometer, watched.', note: 'Zip bags up to about 70 °C. Ethanol boils near 78 °C, so stay well below. Weigh spirit bags down: they float.', buy: [{ name: 'Anova Precision Cooker, Anova', url: 'https://anovaculinary.com/products/anova-precision-cooker' }, { name: 'Joule, Breville', url: 'https://www.breville.com/en-us/product/cs10001' }, { name: 'HydroPro (PolyScience), Breville', url: 'https://www.breville.com/en-us/product/csv700' }] },
  { id: 'dehydrator', name: 'Dehydrator', kind: 'temperature', tier: '$$', what: 'Dried citrus wheels, fruit and powders.', swap: 'The oven on its lowest setting, door ajar.', buy: [{ name: 'Excalibur 10-tray Performance Digital, Excalibur', url: 'https://excaliburdehydrator.com/products/excalibur-performance-digital-dehydrator-10-tray' }, { name: 'Cosori 6-tray stainless, Cosori', url: 'https://cosori.com/products/premium-stainless-steel-food-dehydrator-cp267-fd' }] },
  { id: 'ice-cooler', name: 'Small hard-sided cooler', kind: 'temperature', tier: '$', price: 'Under $50 for a plain cooler; about $100 for one made for clear ice', what: 'Clear ice by freezing from the top down; freeze-concentrating juice.', note: '18 hours for a tray build, about 50 for a full block.', buy: [{ name: 'Ice Chest clear-ice mold, Wintersmiths', url: 'https://www.wintersmiths.com/products/ice-chest' }, { name: 'Phantom clear-ice maker, Wintersmiths', url: 'https://www.wintersmiths.com/products/phantom-ice-maker' }] },
  { id: 'freezer-thermo', name: 'Freezer thermometer', kind: 'temperature', tier: '$', what: 'Knowing your freezer runs -12 °C, not -18 °C, before you batch for it.', note: 'Leave it 12 hours to read true.', buy: [{ name: 'Fridge and freezer thermometer, ThermoWorks', url: 'https://www.thermoworks.com/products/rt8100' }] },
  { id: 'smoke-gun', name: 'Smoke gun and cloche', kind: 'temperature', tier: '$', what: 'Smoke over a drink, a glass or a garnish.', swap: 'A smoker, for syrups and ice.', note: 'Ventilate.', buy: [{ name: 'Smoking Gun Pro, Breville', url: 'https://www.breville.com/en-us/product/csm700' }, { name: 'Smoking Gun Pro cloche, Breville', url: 'https://www.breville.com/en-us/product/csm018clr0nxx1' }, { name: 'Smoking Gun and cloche set, Breville', url: 'https://www.breville.com/en-us/product/bsm620' }] },
  { id: 'freeze-dryer', name: 'Freeze dryer', kind: 'temperature', tier: '$$$', price: 'From about $1,900', what: 'Shelf-stable fruit garnishes and powders that keep their colour.', swap: 'The dehydrator: chewier, darker.', note: 'A batch takes a day or more.', buy: [{ name: 'Home Pro freeze dryer, Harvest Right', url: 'https://harvestright.com/products/home-pro-freeze-dryer-bundle' }] },
  { id: 'torch', name: 'Kitchen torch', kind: 'temperature', tier: '$', what: 'Brûléed garnishes, toasted rims.', swap: 'The grill.', note: 'Let glass cool before it touches liquid.', buy: [{ name: 'Iwatani PRO2 butane torch, Iwatani', url: 'https://www.iwatani.com/Pro-2' }, { name: 'Iwatani PRO2, Amazon', url: 'https://www.amazon.com/dp/B01HVZR3DI' }] },

  { id: 'superbag', name: 'Superbags or nut-milk bags', kind: 'separate', tier: '$', what: 'Every strain step: nut milks, purees, milk punch, fat washes.', note: 'Ratings run 100 to 800 micron. A bag alone won’t clarify; use it before a finer method.', buy: [{ name: 'Superbag 250 micron, Modernist Pantry', url: 'https://modernistpantry.com/products/superbag-250-micron.html' }, { name: 'Superbag 100 micron, Modernist Pantry', url: 'https://modernistpantry.com/products/superbag-100-micron.html' }] },
  { id: 'hotel-pans', name: 'Perforated hotel pans', kind: 'separate', tier: '$', what: 'Freeze-thaw clarifying, and spreading a milk punch wide so it filters faster.', swap: 'A sieve over a bowl.', buy: [{ name: 'Vollrath full-size perforated pan, 2.5 in, WebstaurantStore', url: 'https://www.webstaurantstore.com/vollrath-30023-super-pan-v-full-size-anti-jam-stainless-steel-perforated-steam-table-hotel-pan-2-1-2-deep/92230023.html' }, { name: 'Vollrath full-size perforated pan, 6 in, WebstaurantStore', url: 'https://www.webstaurantstore.com/vollrath-30063-super-pan-v-full-size-anti-jam-stainless-steel-perforated-steam-table-hotel-pan-6-deep/92230063.html' }] },
  { id: 'centrifuge', name: 'Centrifuge (Spinzall)', kind: 'separate', tier: '$$$', price: 'About $1,200 (Spinzall 2.1)', what: 'Clears juice and purees in minutes, with enzymes.', swap: 'Quick agar and a cloth: slower, nearly as clear.', note: 'Treat fruit with Pectinex first. Balance the rotor.', buy: [{ name: 'Spinzall 2.1, Modernist Pantry', url: 'https://modernistpantry.com/products/spinzall-2-1.html' }, { name: 'Spinzall, Booker and Dax', url: 'https://www.bookeranddax.com/spinzall' }] },
  { id: 'vacuum-filter', name: 'Vacuum filtration kit', kind: 'separate', tier: '$$', what: 'Pulls milk punch and clarified juice through filter paper in minutes, not hours.', swap: 'Coffee filters and patience.', note: 'Change the paper when it clogs; pressing it through clouds the result.', buy: [{ name: 'Buchner funnel and 1 L flask kit, TN Lab Supply', url: 'https://www.tnlab.com/products/buchner-funnel-filter-flask-kit-120mm-1000ml' }, { name: 'Oil-free diaphragm vacuum pump, VXB', url: 'https://vxb.com/products/oilless-lab-diaphragm-vacuum-pump-go-to-filtration' }] },

  { id: 'pacojet', name: 'Pacojet', kind: 'specialist', tier: '$$$', price: 'About $7,500 (Pacojet 4)', what: 'Frozen cocktails and sorbets, spun from a frozen block.', swap: 'A blender and a long rest.', note: 'Freeze at -20 °C for 24 hours before it spins.', buy: [{ name: 'Pacojet 4 system, Modernist Pantry', url: 'https://modernistpantry.com/products/pacojet-4-system.html' }, { name: 'Pacojet 4, Pacojet', url: 'https://pacojet.com/en-GB/Pacojet-4/137623-000-00' }] },
  { id: 'rotovap', name: 'Rotary evaporator (Girovap)', kind: 'specialist', tier: '$$$', price: 'About €4,500 (Girovap Pro2), pump extra', what: 'Distils at low temperature: hydrosols and clear distillates.', swap: 'Nitrous or freezer infusions, for flavour.', note: 'Distilling alcohol at a US bar or at home needs a federal (TTB) permit.', buy: [{ name: 'Girovap Pro2, 100%Chef', url: 'https://100x100chef.com/shop/en/vacuum-distillation/1337-girovap-pro2.html' }, { name: 'Girovap range, 100%Chef', url: 'https://100x100chef.com/shop/en/114-girovap' }, { name: 'Hei-VAP Core, Heidolph', url: 'https://heidolph.com/america/en/hei-vap-core-hand-lift-model-with-g3-vertical-glassware~p227' }, { name: 'Rotavapor R-80, Buchi', url: 'https://www.buchi.com/en/products/instruments/rotavapor-r-80' }] },
  { id: 'ultrasonic', name: 'Ultrasonic probe', kind: 'specialist', tier: '$$$', what: 'Fast infusions by cavitation.', swap: 'A nitrous infusion.', note: 'Bath cleaners haven’t been tested for drinks.', buy: [{ name: 'UP200St ultrasonic homogenizer, Hielscher', url: 'https://www.hielscher.com/up200st-powerful-ultrasonic-lab-homogenizer.htm' }] },
  { id: 'ln2', name: 'Liquid nitrogen Dewar and cryo gloves', kind: 'specialist', tier: '$$$', what: 'Instant chilling and freezing.', swap: 'The freezer.', note: 'Training and protective gear. Cryo gloves guard against splashes, never a dip. Never serve a drink with nitrogen still in it.', buy: [{ name: '10 L liquid nitrogen Dewar, MiTeGen', url: 'https://www.mitegen.com/product/10-liter-liquid-dewar/' }, { name: 'Tempshield cryo gloves, mid-arm, Weber Scientific', url: 'https://www.weberscientific.com/tempshield-waterproof-cryo-gloves' }] },
  { id: 'squasher', name: 'Paddle press (Squasher)', kind: 'specialist', tier: '$$$', price: 'About €2,800 at 100%Chef', what: 'Pulls flavour into water, spirit or oil by squeezing ingredients in a bag hundreds of times a minute, cold.', swap: 'A nitrous infusion, or a blend and strain.', note: '80 to 400 ml a batch. No heat, and nothing touches metal, so less oxidation.', buy: [{ name: 'Squasher, 100%Chef', url: 'https://100x100chef.com/shop/en/emulsifiers/247-pressure-homogeneizer-squasher.html' }] },
  { id: 'spheres-kit', name: 'Spherification spoon and caviar maker', kind: 'specialist', tier: '$', what: 'Even spheres from a spoon, or dozens of alginate pearls at once.', swap: 'A measuring spoon, and a syringe for pearls.', buy: [{ name: 'Spherification spoon, Modernist Pantry', url: 'https://modernistpantry.com/products/spherification-spoon.html' }, { name: 'Perfect Caviar Maker, Modernist Pantry', url: 'https://modernistpantry.com/products/perfect-caviar-maker.html' }, { name: 'Caviar Box (96 at once), 100%Chef', url: 'https://100x100chef.com/shop/en/spherifying-machines/178-caviar-box.html' }] },
  { id: 'ferment-kit', name: 'Fermentation weights and airlock lids', kind: 'specialist', tier: '$', what: 'Keeps produce under the brine and lets gas out without letting air in.', swap: 'A zip bag of brine on top, and the lid loose.', buy: [{ name: 'Pickle Pebbles glass weights, Masontops', url: 'https://www.masontops.com/products/pickle-pebbles-plus' }, { name: 'Pickle Pipe airlock lids, Masontops', url: 'https://www.masontops.com/products/pickle-pipe' }] },
  { id: 'swing-tops', name: 'Pressure-rated swing-top bottles', kind: 'specialist', tier: '$', what: 'Second ferments and bottled fizz.', note: 'They build pressure fast in a second ferment. Chill before opening. EZ Cap rates its bottles to 100 psi.', buy: [{ name: 'EZ Cap 16 oz swing-tops, case of 12, MoreBeer', url: 'https://morebeer.com/products/ez-cap-swing-top-bottles-clear-glass-16-oz-case-12' }] },
];

/** A tier in words: only `price` is sourced, so tiers stay rough. */
export const TIER_LABEL: Record<Equipment['tier'], string> = { $: 'Under about $50', $$: 'About $50 to $500', $$$: 'Over about $500' };

const BY_ID = new Map(EQUIPMENT.map((e) => [e.id, e]));

export function equipmentById(id: string): Equipment | undefined {
  return BY_ID.get(id);
}
