import type { Grade, Source } from './types';

/** The sources the library leans on, so entries cite them by key. All free to read; we link, never copy. */
const S = {
  khymos: { name: 'Khymos, Texture (Lersch)', url: 'http://blog.khymos.org/wp-content/2009/02/hydrocolloid-recipe-collection-v3.0.pdf' },
  arnoldAgar: { name: 'Cooking Issues: agar clarification', url: 'https://cookingissues.com/2009/07/14/agar-clarification-made-stupid-simple-best-technique-yet/' },
  arnoldClarify: { name: 'Cooking Issues: clarification rundown', url: 'https://cookingissues.com/2010/07/20/simple-agar-clarification-1-year-anniversary-plus-a-rundown-of-current-clarification-techniques/' },
  arnoldInfusion: { name: 'Cooking Issues: rapid nitrous infusion', url: 'https://cookingissues.com/2010/08/11/infusion-profusion-game-changing-fast-n-cheap-technique/' },
  arnoldDilution: { name: 'Cooking Issues: cocktail science', url: 'https://cookingissues.com/2010/09/08/cocktail-science-in-generalpart-2-of-2/' },
  campariMilk: { name: 'Campari Academy: milk punch guide', url: 'https://www.campariacademy.com/en-us/training/tools-techniques/milk-punch-guide-and-recipes/' },
  franklin: { name: 'Benjamin Franklin, milk punch letter (1763)', url: 'https://founders.archives.gov/documents/Franklin/01-10-02-0188' },
  glanz: { name: 'Mia Glanz: milk punch method', url: 'https://milkpunch.substack.com/p/milk-punch-method' },
  alcademicsMilk: { name: 'Alcademics: milk punch science', url: 'https://alcademics.com/milk-punch-science-and-practice/' },
  punchVeganWash: { name: 'Punch: clarified milk punch techniques', url: 'https://punchdrink.com/articles/clarified-milk-punch-techniques-recipes/' },
  mpKit: { name: 'Modernist Pantry: Spinzall pre-treatment', url: 'https://modernistpantry.com/products/spinzall-pre-treatment-starter-kit.html' },
  mpFoams: { name: 'Modernist Pantry: the secret of foams', url: 'https://blog.modernistpantry.com/wtf/the-secret-of-foams/' },
  mpAcid: { name: 'Modernist Pantry: acid-adjusting juices', url: 'https://blog.modernistpantry.com/advice/how-to-acid-adjust-juices/' },
  mpSpheres: { name: 'Modernist Pantry: reverse spherification', url: 'https://blog.modernistpantry.com/spherification-course/lesson-2-reverse-spherification-2/' },
  mpPowders: { name: 'Modernist Pantry: culinary powders', url: 'https://blog.modernistpantry.com/advice/culinary-powders/' },
  mpGellan: { name: 'Modernist Pantry: carbonated French 75', url: 'https://blog.modernistpantry.com/?p=3039' },
  afmeLecithin: { name: 'Amazing Food Made Easy: lecithin air', url: 'https://www.amazingfoodmadeeasy.com/info/modernist-recipes/more/mustard-soy-lecithin-air' },
  afmeSiphon: { name: 'Amazing Food Made Easy: siphon troubleshooting', url: 'https://www.amazingfoodmadeeasy.com/info/modernist-cooking-blog/more/troubleshooting-your-whipping-siphon' },
  isiManual: { name: 'iSi Gourmet Whip manual', url: 'https://cdnimg.webstaurantstore.com/documents/pdf/416180101.pdf' },
  totcShake: { name: 'Tales of the Cocktail: reverse dry shake', url: 'https://talesofthecocktail.org/why-reverse-shake-yields-perfect-egg-white-foam/' },
  punchSourSyrup: { name: 'Punch: methylcellulose sour syrup', url: 'https://punchdrink.com/recipes/sour-syrup/' },
  punchFoamers: { name: 'Punch: vegan foamers', url: 'https://punchdrink.com/articles/better-froth-cocktail-vegan-aquafaba-fee-brothers-foam/' },
  tylopur: { name: 'SE Tylose: cocktail foams', url: 'https://www.setylose.com/fileadmin/user_upload/Recipe_Cocktail_Foams_with_Tylopur_MCE-4000.pdf' },
  diffordsSyrup: { name: 'Difford’s: rich vs simple syrup', url: 'https://www.diffordsguide.com/en-au/encyclopedia/3593/cocktails/2-to-1-rich-sugar-syrup-versus-1-to-1-simple-syrup' },
  punchHoney: { name: 'Punch: cocktail syrups', url: 'https://punchdrink.com/articles/not-too-sweet-ok-how-to-use-simple-demerara-cane-honey-agave-cocktail-syrup/' },
  vitamix: { name: 'Vitamix: simple syrup', url: 'https://vitamix.com/us/en_us/recipes/simple-syrup' },
  imbibeGomme: { name: 'Imbibe: gomme syrup', url: 'https://imbibemagazine.com/recipe/gomme-syrup-recipe' },
  morgenthalerOleo: { name: 'Jeffrey Morgenthaler: oleo saccharum', url: 'https://jeffreymorgenthaler.com/?p=1993' },
  ruhlmanCordial: { name: 'Ruhlman: Morgenthaler’s lime cordial', url: 'https://ruhlman.com/wprm_print/lime-cordial-by-jeffrey-morganthaler' },
  ucShrub: { name: 'UC ANR: shrubs', url: 'https://www.ccfruitandnuts.ucanr.edu/sites/default/files/2023-10/389540.pdf' },
  campariAcid: { name: 'Campari Academy: acid solution', url: 'https://www.campariacademy.com/en-us/inspiration/trends/acid-solution/' },
  atkSaline: { name: 'America’s Test Kitchen: saline', url: 'https://www.americastestkitchen.com/articles/6186-this-ingredient-makes-every-cocktail-pop' },
  vinepairSuper: { name: 'VinePair: super juice', url: 'https://vinepair.com/articles/what-is-super-juice-citrus/' },
  inTheKitchOrgeat: { name: 'In the Kitch: orgeat', url: 'https://inthekitch.net/orgeat/' },
  diffordsGrenadine: { name: 'Difford’s: grenadine', url: 'https://www.diffordsguide.com/en-au/beer-wine-spirits/category/803/pomegranate-grenadine-syrup' },
  drinksWorldFat: { name: 'Drinks World: fat washing', url: 'https://drinksworld.com/fat-washing-guide/' },
  punchFatWash: { name: 'Punch: fat washing', url: 'https://punchdrink.com/?p=1261' },
  anovaInfuse: { name: 'Anova: cherry bourbon', url: 'https://recipes.anovaculinary.com/recipe/fresh-cherry-infused-bourbon' },
  sousVideSupreme: { name: 'Sous Vide Supreme: infused spirits', url: 'https://blog.sousvidesupreme.com/2011/01/sous-vide-infused-alcohols-syrups/' },
  atkBitters: { name: 'America’s Test Kitchen: aromatic bitters', url: 'https://www.americastestkitchen.com/recipes/13460-old-fashioned-aromatic-bitters' },
  msuGarlic: { name: 'Michigan State Extension: garlic in oil', url: 'https://www.canr.msu.edu/resources/michigan_fresh_garlic' },
  punchCarbonate: { name: 'Punch: force-carbonated cocktails', url: 'https://punchdrink.com/articles/maximalists-guide-to-force-carbonated-cocktails/' },
  punchIsiFizz: { name: 'Punch: batching fizz with an iSi', url: 'https://punchdrink.com/articles/better-way-to-batch-and-fizz-carbonated-cocktails-isi-technique/' },
  ufCo2: { name: 'UF/IFAS: carbonation volumes', url: 'https://ask.ifas.ufl.edu/publication/FS379' },
  punchFreezer: { name: 'Punch: freezer Martini and Negroni', url: 'https://punchdrink.com/articles/guide-batch-freezer-martini-negroni/' },
  alcademicsIce: { name: 'Alcademics: clear ice', url: 'https://alcademics.com/?p=3179' },
  fdaLn2: { name: 'FDA warning on liquid nitrogen (Food Dive)', url: 'https://www.fooddive.com/news/as-injuries-mount-fda-warns-consumers-on-liquid-nitrogen-drinks-desserts/531605/' },
  aBarAboveCryo: { name: 'A Bar Above: juice concentrate', url: 'https://abarabove.com/juice-concentrate/' },
  lactoSalt: { name: 'Revolution Fermentation: salt for ferments', url: 'https://revolutionfermentation.com/en/blogs/fermented-vegetables/how-much-salt-fermenting-vegetables/' },
  atkTepache: { name: 'America’s Test Kitchen: tepache', url: 'https://www.americastestkitchen.com/recipes/17759-tepache' },
  vtKombucha: { name: 'Virginia Tech Extension: kombucha', url: 'https://pubs.ext.vt.edu/FST/FST-297/FST-297' },
  ucPickles: { name: 'UC Master Food Preservers: quick pickles', url: 'https://ccfruitandnuts.ucanr.edu/sites/default/files/2025-07/MFP%20Quick%20Refrigerator%20Pickles.pdf' },
  campariDehydrate: { name: 'Campari Academy: dehydrated citrus', url: 'https://www.campariacademy.com/en-us/training/how-to-make-dehydrated-citrus-garnish/' },
  breville: { name: 'Breville: smoking gun', url: 'https://breville.com/inspiration/en-us/recipes/specialty-appliances/smoking-in-the-side-car' },
  ttb: { name: 'TTB: home distilling', url: 'https://www.ttb.gov/spirits/home-distilling.shtml' },
  punchRotovap: { name: 'Punch: rotovap in bars', url: 'https://punchdrink.com/articles/rotovap-distillation-cocktail-bars/' },
  specialSuspension: { name: 'Special Ingredients: suspension syrup', url: 'https://recipes.specialingredientseurope.com/en/suspension-syrup-recipe/' },
  patentGellan: { name: 'US patent 5562939 (gellan in drinks)', url: 'https://image-ppubs.uspto.gov/dirsearch-public/print/downloadPdf/5562939' },
  anovaChamber: { name: 'Anova: chamber vacuum recipes', url: 'https://anovaculinary.com/en-tw/pages/chamber-vacuum-sealer-recipes' },
  coldBrew: { name: 'My Coffee Explorer: cold brew ratios', url: 'https://mycoffeeexplorer.com/reference/cold-brew-ratios' },
  efsaGlycerol: { name: 'EFSA: glycerol in drinks (PubMed)', url: 'https://pubmed.ncbi.nlm.nih.gov/42095189/' },
  brewhausGlycerin: { name: 'Brewhaus: glycerin', url: 'https://old.brewhaus.com/glycerin-4oz' },
  pacojet: { name: 'Pacojet: Campari sorbet', url: 'https://pacojet.com/en-GB/Recipes/Ice-cream-and-sorbet/Campari-Sorbet/' },
} as const;

export type SourceKey = keyof typeof S;

/** A source with how far to trust it for this particular entry. */
export function src(key: SourceKey, grade: Grade): Source {
  return { ...S[key], grade };
}
